/* Body file for function Receiver019
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "receiver019_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void receiver019_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void CInitreceiver019(void);

unsigned receiver019_initialized = 0;
void init_receiver019(void)
{
   if (0 == receiver019_initialized) {
      receiver019_initialized = 1;
      // Call user code startup function
      extern void receiver019_startup(void);
      receiver019_startup();
      receiver019_initialized = 2;
   }
}
void receiver019_PI_1_SR19
      (char *OUT_p1, size_t *OUT_p1_len)

{
   sender_pid = receiver019_pi_1_sr19_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void receiver019_PI_PI_1_SR19
      (asn1SccT_Int32 *);





   // Call user code
   receiver019_PI_PI_1_SR19 ((asn1SccT_Int32 *)OUT_p1);

}

