/* Header file for function Receiver018
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void receiver018_startup(void);

/* Provided interfaces */
void receiver018_PI_PI_1_SR18( asn1SccT_Int32 * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
