/* Body file for function Function_3
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "function_3.h"
//#include <stdio.h>


void function_3_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[Function_3] Startup");
}

//
// Note, this function is being called only to prove
//       both cyclic and spradic interfaces
//
void function_3_PI_PI_cyclic_3( void )
{
    int counter = 0;

    // This is a mandatory cycle interface, which will
    // be received, a counter will be implemented
    if ( counter > 2147483000 )
    {
        counter = 0;
    }

    counter++;
}

//
// function_3_PI_PI_3 receives a message from function_2_PI_PI_2
//
void function_3_PI_PI_3( const asn1SccT_Int32 * data_in )
{
    asn1SccT_Int32 data = 0;

    data = *data_in + 1;
    // Send the data to the next function (4)
    function_3_RI_PI_4( &data );

}


