/* Body file for function test_invocations
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "test_invocations.h"
//#include <stdio.h>


void test_invocations_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[test_invocations] Startup");
}

void test_invocations_PI_p1(void)
{
   // Write your code here
}


void test_invocations_PI_p2(void)
{
   // Write your code here
}


void test_invocations_PI_p3(void)
{
   // Write your code here
}


void test_invocations_PI_p4(void)
{
   // Write your code here
}


void test_invocations_PI_p5(void)
{
   // Write your code here
}


void test_invocations_PI_p6(void)
{
   // Write your code here
}


void test_invocations_PI_p7(void)
{
   // Write your code here
}


void test_invocations_PI_p8(void)
{
   // Write your code here
}


void test_invocations_PI_p9(void)
{
   // Write your code here
}


void test_invocations_PI_p10(void)
{
    // Write your code here
}


void test_invocations_PI_trigger_check(void)
{
   // Write your code here
}


