/* Header file for function BrokerTest002A
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void brokertest002a_startup(void);

/* Provided interfaces */
void brokertest002a_PI_PI_1( asn1SccT_Int32 *, asn1SccT_Boolean * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
