pragma Style_Checks (Off);
--  Code automatically generated by asn1scc tool

pragma Warnings (Off, """String"" is already use-visible inside package ""Standard""");

pragma Warnings (Off, "redundant with clause in body");
pragma Warnings (On, "redundant with clause in body");

package body MODEL_TF1_DATAVIEW with SPARK_Mode is


pragma Warnings (Off, "condition can only be False if invalid values present");
pragma Warnings (Off, "condition can only be True if invalid values present");


function asn1SccMyInteger_Equal (val1, val2 :  asn1SccMyInteger) return Boolean
is

begin
	return val1 = val2;

end asn1SccMyInteger_Equal;

function asn1SccMyInteger_IsConstraintValid(val : asn1SccMyInteger) return adaasn1rtl.ASN1_RESULT
is
    pragma Warnings (Off, "initialization of ""ret"" has no effect");
    ret : adaasn1rtl.ASN1_RESULT := adaasn1rtl.ASN1_RESULT'(Success => true, ErrorCode => 0);
    pragma Warnings (On, "initialization of ""ret"" has no effect");
begin
    ret.Success := (val <= 10000);
    ret.ErrorCode := (if ret.Success then 0 else ERR_MYINTEGER);
    return ret;
end asn1SccMyInteger_IsConstraintValid;





function asn1SccCounter_Equal (val1, val2 :  asn1SccCounter) return Boolean
is

begin
	return val1 = val2;

end asn1SccCounter_Equal;

function asn1SccCounter_IsConstraintValid(val : asn1SccCounter) return adaasn1rtl.ASN1_RESULT
is
    pragma Warnings (Off, "initialization of ""ret"" has no effect");
    ret : adaasn1rtl.ASN1_RESULT := adaasn1rtl.ASN1_RESULT'(Success => true, ErrorCode => 0);
    pragma Warnings (On, "initialization of ""ret"" has no effect");
begin
    ret.Success := (val <= 1000);
    ret.ErrorCode := (if ret.Success then 0 else ERR_COUNTER);
    return ret;
end asn1SccCounter_IsConstraintValid;




pragma Warnings (On, "condition can only be False if invalid values present");
pragma Warnings (On, "condition can only be True if invalid values present");

end MODEL_TF1_DATAVIEW;