pragma Style_Checks (Off);
--  Code automatically generated by asn1scc tool
pragma Warnings (Off, "no entities of ""Interfaces"" are referenced");
with Interfaces;
pragma Warnings (On, "no entities of ""Interfaces"" are referenced");

pragma Warnings (Off, "use clause for package ""Interfaces"" has no effect");
use Interfaces;
pragma Warnings (On, "use clause for package ""Interfaces"" has no effect");

with adaasn1rtl;


pragma Warnings (Off, "unit ""System"" is not referenced");
with System;
pragma Warnings (On, "unit ""System"" is not referenced");

pragma Warnings (Off, "use clause for package ""adaasn1rtl"" has no effect");
use adaasn1rtl;
pragma Warnings (On, "use clause for package ""adaasn1rtl"" has no effect");

pragma Warnings (Off, "use clause for type");
pragma Warnings (Off, "is already use-visible through package use clause at line");
use type adaasn1rtl.OctetBuffer;
use type adaasn1rtl.BitArray;
use type adaasn1rtl.Asn1UInt;
use type adaasn1rtl.Asn1Int;
use type adaasn1rtl.BIT;
pragma Warnings (On, "use clause for type");
pragma Warnings (On, "is already use-visible through package use clause at line");

pragma Warnings (Off, "no entities of ""System_Dataview"" are referenced");
pragma Warnings (Off, "use clause for package ""System_Dataview"" has no effect");
with System_Dataview; use System_Dataview;
pragma Warnings (On, "no entities of ""System_Dataview"" are referenced");
pragma Warnings (On, "use clause for package ""System_Dataview"" has no effect");

pragma Warnings (Off, "no entities of ""MODEL_TF1_DATAVIEW"" are referenced");
pragma Warnings (Off, "use clause for package ""MODEL_TF1_DATAVIEW"" has no effect");
with MODEL_TF1_DATAVIEW; use MODEL_TF1_DATAVIEW;
pragma Warnings (On, "no entities of ""MODEL_TF1_DATAVIEW"" are referenced");
pragma Warnings (On, "use clause for package ""MODEL_TF1_DATAVIEW"" has no effect");



package Testsdl14_Datamodel with SPARK_Mode
is


subtype asn1SccTestsdl14_States_index_range is Integer range 0..0;
type asn1SccTestsdl14_States is (asn1Sccwait) with Size => adaasn1rtl.Enumerated_Size;
for asn1SccTestsdl14_States use
    (asn1Sccwait => 0);

function asn1SccTestsdl14_States_Equal(val1, val2 : asn1SccTestsdl14_States) return Boolean;

ERR_TESTSDL14_STATES:constant Integer := 1; -- wait
function asn1SccTestsdl14_States_IsConstraintValid(val : asn1SccTestsdl14_States) return adaasn1rtl.ASN1_RESULT;

function asn1SccTestsdl14_States_Init  return asn1SccTestsdl14_States is
(asn1Sccwait);
-- asn1SccTestsdl14_Context --------------------------------------------

type asn1SccTestsdl14_Context is record
    state : asn1SccTestsdl14_States;
    init_done : adaasn1rtl.Asn1Boolean;
    sender : System_Dataview.asn1SccPID;
    offspring : System_Dataview.asn1SccPID;
    counter : MODEL_TF1_DATAVIEW.asn1SccCounter;
end record;


function asn1SccTestsdl14_Context_Equal(val1, val2 : asn1SccTestsdl14_Context) return Boolean;

ERR_TESTSDL14_CONTEXT:constant Integer := 141; -- 
ERR_TESTSDL14_CONTEXT_STATE_2:constant Integer := 101; -- 
ERR_TESTSDL14_CONTEXT_INIT_DONE:constant Integer := 106; -- 
ERR_TESTSDL14_CONTEXT_SENDER_2:constant Integer := 116; -- 
ERR_TESTSDL14_CONTEXT_OFFSPRING_2:constant Integer := 126; -- 
ERR_TESTSDL14_CONTEXT_COUNTER_2:constant Integer := 136; -- 
function asn1SccTestsdl14_Context_IsConstraintValid(val : asn1SccTestsdl14_Context) return adaasn1rtl.ASN1_RESULT;

function asn1SccTestsdl14_Context_Init  return asn1SccTestsdl14_Context is
((state => asn1Sccwait, init_done => False, sender => System_Dataview.asn1Sccactivationlog, offspring => System_Dataview.asn1Sccactivationlog, counter => 0));
subtype asn1SccTestsdl14_T_Runtime_Error_Selection_index_range is Integer range 0..2;
type asn1SccTestsdl14_T_Runtime_Error_Selection is (asn1Sccnoerror_present, asn1Sccencodeerror_present, asn1Sccdecodeerror_present) with Size => adaasn1rtl.Enumerated_Size;
for asn1SccTestsdl14_T_Runtime_Error_Selection use
    (asn1Sccnoerror_present => 1, asn1Sccencodeerror_present => 2, asn1Sccdecodeerror_present => 3);

function asn1SccTestsdl14_T_Runtime_Error_Selection_Equal(val1, val2 : asn1SccTestsdl14_T_Runtime_Error_Selection) return Boolean;

ERR_TESTSDL14_T_RUNTIME_ERROR_SELECTION:constant Integer := 6; -- noerror-present | encodeerror-present | decodeerror-present
function asn1SccTestsdl14_T_Runtime_Error_Selection_IsConstraintValid(val : asn1SccTestsdl14_T_Runtime_Error_Selection) return adaasn1rtl.ASN1_RESULT;

function asn1SccTestsdl14_T_Runtime_Error_Selection_Init  return asn1SccTestsdl14_T_Runtime_Error_Selection is
(asn1Sccnoerror_present);
pragma Warnings (Off, "there are no others");
pragma Warnings (On, "there are no others");
private
   --# hide Testsdl14_Datamodel;


end Testsdl14_Datamodel;