/* Body file for function Receiver012
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "receiver012_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void receiver012_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void CInitreceiver012(void);

unsigned receiver012_initialized = 0;
void init_receiver012(void)
{
   if (0 == receiver012_initialized) {
      receiver012_initialized = 1;
      // Call user code startup function
      extern void receiver012_startup(void);
      receiver012_startup();
      receiver012_initialized = 2;
   }
}
void receiver012_PI_1_SR12
      (const char *IN_p1, size_t IN_p1_len,
       char *OUT_p2, size_t *OUT_p2_len)

{
   sender_pid = receiver012_pi_1_sr12_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void receiver012_PI_PI_1_SR12
      (const asn1SccT_Int32 *,
       asn1SccT_Boolean *);





   // Call user code
   receiver012_PI_PI_1_SR12 ((asn1SccT_Int32 *)IN_p1, (asn1SccT_Boolean *)OUT_p2);

}

