/* Body file for function TestProtected
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "testprotected_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void testprotected_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void CInittestprotected(void);

extern void init_prot00if(void);
extern unsigned prot00if_initialized;
extern void init_prot05ifin(void);
extern unsigned prot05ifin_initialized;
extern void init_prot05ifout(void);
extern unsigned prot05ifout_initialized;
unsigned testprotected_initialized = 0;
void init_testprotected(void)
{
   if (0 == testprotected_initialized) {
      testprotected_initialized = 1;
      // Call user code startup function
      extern void testprotected_startup(void);
      testprotected_startup();
      // Iterate over all synchronous RIs, and call their parent's
      // init function. Multiple calls are prevented by the "init" guard.
      if (0 == prot00if_initialized) {
          init_prot00if();
      }
      if (0 == prot05ifin_initialized) {
          init_prot05ifin();
      }
      if (0 == prot05ifout_initialized) {
          init_prot05ifout();
      }
      testprotected_initialized = 2;
   }
}
void testprotected_PI_1_Prot_Start
      (char *OUT_p1, size_t *OUT_p1_len,
       char *OUT_p2, size_t *OUT_p2_len)

{
   sender_pid = testprotected_pi_1_prot_start_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void testprotected_PI_PI_1_Prot_Start
      (asn1SccT_Int32 *,
       asn1SccT_Boolean *);





   // Call user code
   testprotected_PI_PI_1_Prot_Start ((asn1SccT_Int32 *)OUT_p1, (asn1SccT_Boolean *)OUT_p2);

}

