/* Body file for function log_flooder
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "log_flooder.h"
#include <Monitor.h>
#include "../../../../../tf_common/tf_uart_comms.h"
#include <stdio.h>


// Each Sporadic interface call results in two log entries: one for activation and one for deactivation.
// The intent is to flood the activation log such that it overflows (cyclic buffer)
#define NUM_SPORADIC_IF_CALLS   1000


// Constructor (unused)
void log_flooder_startup(void)
{
}


// Cyclic IF handler. Enables and clears the activation log, then floods it with entries
void log_flooder_PI_trigger_flood(void)
{
    char aMsgBuff[100];

    // Clear the log, which will also enable logging
    Monitor_ClearInterfaceActivationLog();

    // Enable the logging
    Monitor_UnfreezeInterfaceActivationLogging();

    // Now call the Sporadic interface 100 times, which will result in 200 log entries (activation and deactivation for each call)
    for (int i = 0; i < NUM_SPORADIC_IF_CALLS; i++) {
        log_flooder_RI_sporadic_if();
    }

    // Report what we did
    sprintf(aMsgBuff, "Flooded the activation log with %d entries", (NUM_SPORADIC_IF_CALLS * 2) + 1); // Add one for the inevitable "deactivation" of this IF call (this)
    transmit_log_info(aMsgBuff);
}



