#!/usr/bin/env python3

#  Automatically generated by kazoo/templates/glue/language_wrappers/mini-cv-python
#  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
#  This is an input file for the DMT tool "aadl2glueC". It is imported
#  at runtime and its role is to populate DMT's AST prior to executing the
#  B mapper functions.

from dmt.commonPy import aadlAST as ast

ast.g_apLevelContainers = dict()

# Interface "PI_1"
sp = ast.ApLevelContainer("PI_1")
ast.g_apLevelContainers["PI_1"] = sp
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::T_Int32")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("p1", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "T_Int32"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("PI_1", "p1", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("PI_1", "p1", signal, spFeature._parameter)
    sp.AddParam(param)
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::T_UInt32")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("p2", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "T_UInt32"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("PI_1", "p2", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("PI_1", "p2", signal, spFeature._parameter)
    sp.AddParam(param)
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::T_Int8")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("p3", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "T_Int8"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("PI_1", "p3", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("PI_1", "p3", signal, spFeature._parameter)
    sp.AddParam(param)
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::T_UInt8")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("p4", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "T_UInt8"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("PI_1", "p4", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("PI_1", "p4", signal, spFeature._parameter)
    sp.AddParam(param)
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::T_Boolean")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("p5", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "T_Boolean"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("PI_1", "p5", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("PI_1", "p5", signal, spFeature._parameter)
    sp.AddParam(param)
subProgramParameters = []
param = ast.AadlParameter("OUT", "DataView::T_Boolean")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("p6", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "T_Boolean"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("PI_1", "p6", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("PI_1", "p6", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = PI_1
# Taste::RCMoperationKind = unprotected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = C
ast.g_subProgramImplementations.append(["PI_1", "C", "C", "testunprotout05", sp._fpgaConfigurations])
sp._language = "C"



