--  Generated by TASTE  (kazoo/templates/skeletons/ada-source/function.tmplt)
--  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD

with Model_Tf1_Dataview; use Model_Tf1_Dataview;
with Taste_Basictypes;   use Taste_Basictypes;
with System_Dataview;    use System_Dataview;

-- Access to required interfaces is specified in this package:
with Adatest_RI; use Adatest_RI;

package Adatest is


   procedure Pi_1 (P1 : in out asn1SccT_Boolean)
      with Export,
           Convention => C,
           Link_Name  => "adatest_PI_PI_1";

end Adatest;
