/* Body file for function Receiver001
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "receiver001_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void receiver001_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void CInitreceiver001(void);

unsigned receiver001_initialized = 0;
void init_receiver001(void)
{
   if (0 == receiver001_initialized) {
      receiver001_initialized = 1;
      // Call user code startup function
      extern void receiver001_startup(void);
      receiver001_startup();
      receiver001_initialized = 2;
   }
}
void receiver001_PI_1
      (const char *IN_p1, size_t IN_p1_len,
       char *OUT_p2, size_t *OUT_p2_len)

{
   sender_pid = receiver001_pi_1_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void receiver001_PI_PI_1
      (const asn1SccT_Int32 *,
       asn1SccT_Boolean *);





   // Call user code
   receiver001_PI_PI_1 ((asn1SccT_Int32 *)IN_p1, (asn1SccT_Boolean *)OUT_p2);

}




void receiver001_PI_10
      (const char *IN_p1, size_t IN_p1_len,
       char *OUT_p2, size_t *OUT_p2_len)

{
   sender_pid = receiver001_pi_10_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void receiver001_PI_PI_10
      (const asn1SccT_Int32 *,
       asn1SccT_Boolean *);





   // Call user code
   receiver001_PI_PI_10 ((asn1SccT_Int32 *)IN_p1, (asn1SccT_Boolean *)OUT_p2);

}




void receiver001_PI_2
      (const char *IN_p1, size_t IN_p1_len,
       char *OUT_p2, size_t *OUT_p2_len)

{
   sender_pid = receiver001_pi_2_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void receiver001_PI_PI_2
      (const asn1SccT_Int32 *,
       asn1SccT_Boolean *);





   // Call user code
   receiver001_PI_PI_2 ((asn1SccT_Int32 *)IN_p1, (asn1SccT_Boolean *)OUT_p2);

}




void receiver001_PI_3
      (const char *IN_p1, size_t IN_p1_len,
       char *OUT_p2, size_t *OUT_p2_len)

{
   sender_pid = receiver001_pi_3_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void receiver001_PI_PI_3
      (const asn1SccT_Int32 *,
       asn1SccT_Boolean *);





   // Call user code
   receiver001_PI_PI_3 ((asn1SccT_Int32 *)IN_p1, (asn1SccT_Boolean *)OUT_p2);

}




void receiver001_PI_4
      (const char *IN_p1, size_t IN_p1_len,
       char *OUT_p2, size_t *OUT_p2_len)

{
   sender_pid = receiver001_pi_4_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void receiver001_PI_PI_4
      (const asn1SccT_Int32 *,
       asn1SccT_Boolean *);





   // Call user code
   receiver001_PI_PI_4 ((asn1SccT_Int32 *)IN_p1, (asn1SccT_Boolean *)OUT_p2);

}




void receiver001_PI_5
      (const char *IN_p1, size_t IN_p1_len,
       char *OUT_p2, size_t *OUT_p2_len)

{
   sender_pid = receiver001_pi_5_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void receiver001_PI_PI_5
      (const asn1SccT_Int32 *,
       asn1SccT_Boolean *);





   // Call user code
   receiver001_PI_PI_5 ((asn1SccT_Int32 *)IN_p1, (asn1SccT_Boolean *)OUT_p2);

}




void receiver001_PI_6
      (const char *IN_p1, size_t IN_p1_len,
       char *OUT_p2, size_t *OUT_p2_len)

{
   sender_pid = receiver001_pi_6_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void receiver001_PI_PI_6
      (const asn1SccT_Int32 *,
       asn1SccT_Boolean *);





   // Call user code
   receiver001_PI_PI_6 ((asn1SccT_Int32 *)IN_p1, (asn1SccT_Boolean *)OUT_p2);

}




void receiver001_PI_7
      (const char *IN_p1, size_t IN_p1_len,
       char *OUT_p2, size_t *OUT_p2_len)

{
   sender_pid = receiver001_pi_7_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void receiver001_PI_PI_7
      (const asn1SccT_Int32 *,
       asn1SccT_Boolean *);





   // Call user code
   receiver001_PI_PI_7 ((asn1SccT_Int32 *)IN_p1, (asn1SccT_Boolean *)OUT_p2);

}




void receiver001_PI_8
      (const char *IN_p1, size_t IN_p1_len,
       char *OUT_p2, size_t *OUT_p2_len)

{
   sender_pid = receiver001_pi_8_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void receiver001_PI_PI_8
      (const asn1SccT_Int32 *,
       asn1SccT_Boolean *);





   // Call user code
   receiver001_PI_PI_8 ((asn1SccT_Int32 *)IN_p1, (asn1SccT_Boolean *)OUT_p2);

}




void receiver001_PI_9
      (const char *IN_p1, size_t IN_p1_len,
       char *OUT_p2, size_t *OUT_p2_len)

{
   sender_pid = receiver001_pi_9_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void receiver001_PI_PI_9
      (const asn1SccT_Int32 *,
       asn1SccT_Boolean *);





   // Call user code
   receiver001_PI_PI_9 ((asn1SccT_Int32 *)IN_p1, (asn1SccT_Boolean *)OUT_p2);

}

