/* Body file for function Trigger_Function
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "trigger_function.h"
#include "../../../../../tf_common/tf_uart_comms.h"
#include <Hal.h>
#include <stdio.h>


// We only want to fire the start trigger on the Sporadic interface chain once
static asn1SccT_Boolean bFiredOnceAlready = false;

void trigger_function_startup(void)
{
}

void trigger_function_PI_trigger(void)
{
    // Already done this once?
    if (bFiredOnceAlready) {
        return;
    }

    // Log our invocation
    char aMsgBuff[100];
    sprintf(aMsgBuff, "trigger-function is ALIVE!. Uptime: %llu seconds", Hal_GetElapsedTimeInNs() / 1000000000);
    transmit_log_info(aMsgBuff);

    // Start the Sporadic interface chain, passing in an empty bitfield, with just the zeroth bit set
    asn1SccT_UInt32 iNextValue = 1;
    trigger_function_RI_sp(&iNextValue);

    // Set the flag to avoid doing this a second time
    bFiredOnceAlready = true;
}


