--  Stub generated by OpenGEODE.
--  You can edit this file, it will not be overwritten

package body Testsdl08_RI is
   procedure get_sender (sender : out asn1SccPID; Dest_PID : asn1SccPID := asn1SccEnv) is null;
   procedure get_last_error (err : out asn1SccT_Runtime_Error; Dest_PID : asn1SccPID := asn1SccEnv) is null;
   procedure SET_mytime (Val : in out asn1SccT_UInt32; Dest_PID : asn1SccPID := asn1SccEnv) is null;
   procedure RESET_mytime (Dest_PID : asn1SccPID := asn1SccEnv) is null;
end Testsdl08_RI;