/* Header file for function UartOtherEnd
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void uartotherend_startup(void);

/* Provided interfaces */
void uartotherend_PI_samrh71tx( const asn1SccT_UInt8 * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
