/* Body file for function SendACN
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "sendacn.h"
#include "limits.h"
#include "../../../../test_defines.h"           // Custom include, NOT managed by TASTE
#include <stdio.h>


void sendacn_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[SendACN] Startup");
}


/************************************************************
 * <Test ID>
 * <SendACN>
 * <Purpose>
 * This test calls 5 receive functions, using unprotected interfaces.
 * An ACN type will be sent, decoded and encoded when each receiver
 * returns the ACN type.
 * <Requirements>
 *  - MBEP-RT-FUN-50
 *  - MBEP-RT-FUN-150
 *  - MBEP-RT-FUN-190
 *  - MBEP-RT-FUN-240
 *  - MBEP-RT-FUN-250
 *  - MBEP-RT-FUN-340
 * <inputs specification>
 * <outputs specification>
 * <Procedure: Proceed steps>
 * - Set up Parameters
 * Call 5 functions using UnProtected Interfaces from a single send interface
 * in order to meet above requirements, varying values sent to functions, which
 * are sent an ACN value decoded and return an ACN encoded value.
 *<Test failure>
 * - Test will fail if any functions call fails to complete, returning
 *   execution to the testfunction.
 * - Test will fail if the passed parameter is incorrect or the received parameter
 *   in incorrect.
 *   Both the Sender and Receiver validate test the encoded and decode parameters.
 *************************************************************/

void sendacn_PI_PI_1
        ( asn1SccT_Int32 *Framework_Result, asn1SccT_Boolean *Framework_Status )
{
asn1SccT_Int32 integer_32_value = 0;
asn1SccT_Int32 integer_32_result = 0;
asn1SccT_UInt8 unsigned_08_value;
asn1SccT_UInt8 unsigned_08_result;
asn1SccT_Boolean Boolean_value;
asn1SccT_Boolean Boolean_result;
asn1SccPID PID_value;
asn1SccPID PID_result;
asn1SccPID_Range PID_Range_Value;
asn1SccPID_Range PID_Range_result;
asn1SccT_Int32 Test_Result = 0;

    // A PID is a process Instance Identified or Process ID (PID)
    // Is a number attached to each SDL function or process in the
    // the system.


    // This test shall encode and ecode ACN values
    // between interfaces.
    // ACN parameters of different sizes shall be sent to
    // respectic Receive function, that function shall
    // return the value with a calculation applied
    // to verify correct encode and decode Taste Runtime functions.

    // ---------------------------------------------
    // --                                         --
    // -- 32 bit Integer Tests, ZERO, MAX and MIN --
    // --                                         --
    // ---------------------------------------------

    integer_32_value = 0;
    integer_32_result = INT_MAX;
    Test_Result = 0;                // First Initialisation, this will count
                                    // Sucessful test results
    *Framework_Status = true;       // PASS, any failure will set this to FALSE

    sendacn_RI_PI_1_ACN_01( &integer_32_value , &integer_32_result );

    *Framework_Result = TestACNCoverstion_TestACN01;
    if ( integer_32_result == INT_MAX )
    {
        *Framework_Status = true;
        if ( PRINT_RESULTS )
        {
            printf( "<TEST_ID> SendACN \n");
            printf("<TEST_RESULT> PASS \n");
        }
    }
    else
    {
        *Framework_Status = false; // FAIL
        if ( PRINT_RESULTS )
        {
            printf("<TEST_ID> SendACN \n");
            printf("<TEST_RESULT> FAIL \n");
            printf("<TEST_FAIL_REASON> TestACNCoverstion_TestACN01 \n");
        }
    }

    unsigned_08_value = UCHAR_MAX;
    unsigned_08_result = 0;

    sendacn_RI_PI_1_ACN_02( &unsigned_08_value , &unsigned_08_result );

    *Framework_Result = TestACNCoverstion_TestACN02;
    if ( unsigned_08_result == UCHAR_MAX )
    {
        *Framework_Status = true;
        if ( PRINT_RESULTS )
        {
            printf( "<TEST_ID> SendACN \n");
            printf("<TEST_RESULT> PASS \n");
        }
    }
    else
    {
        *Framework_Status = false; // FAIL
        if ( PRINT_RESULTS )
        {
            printf("<TEST_ID> SendACN \n");
            printf("<TEST_RESULT> FAIL \n");
            printf("<TEST_FAIL_REASON> TestACNCoverstion_TestACN02 \n");
        }
    }

    Boolean_value = true;
    Boolean_result = 0;

    sendacn_RI_PI_1_ACN03( &Boolean_value , &Boolean_result );

    *Framework_Result = TestACNCoverstion_TestACN03;
    if ( Boolean_result == true )
    {
        *Framework_Status = true; // PASS
        if ( PRINT_RESULTS )
        {
            printf( "<TEST_ID> SendACN \n");
            printf("<TEST_RESULT> PASS \n");
        }
    }
    else
    {
        *Framework_Status = false; // FAIL
        if ( PRINT_RESULTS )
        {
            printf("<TEST_ID> SendACN \n");
            printf("<TEST_RESULT> FAIL \n");
            printf("<TEST_FAIL_REASON> TestACNCoverstion_TestACN03 \n");
        }
    }

    // -- PID_value is the first enumeration item
    // -- PID_result
    PID_value = PID_activationlog;
    PID_result = PID_env;

    sendacn_RI_PI_1_ACN04( &PID_value, &PID_result );

    *Framework_Result = TestACNCoverstion_TestACN04;
    if ( PID_result == PID_activationlog )
    {
        *Framework_Status = true; // PASS
        if ( PRINT_RESULTS )
        {
            printf( "<TEST_ID> SendACN \n");
            printf("<TEST_RESULT> PASS \n");
        }
    }
    else
    {
        *Framework_Status = false; // FAIL
        if ( PRINT_RESULTS )
        {
            printf("<TEST_ID> SendACN \n");
            printf("<TEST_RESULT> FAIL \n");
            printf("<TEST_FAIL_REASON> TestACNCoverstion_TestACN04 \n");
        }
    }



    // ----------------------------------------------------------------------
    // --                                                                  --
    // -- PID Process Instance Identified or Process ID                    --
    // -- Taste Builds a list of PID's based on the function               --
    // -- names in a list identified from 0..n, which is regenerated       --
    // -- everybuild within "dataview-uniq.h" enum type "asn1SccPID"       --
    // -- Macros are defined for each enumeration.                         --
    // --                                                                  --
    // -- This test will test min "asn1SccPID_boothelper00f" to "PID_env"  --
    // -- This test will attempt to test an invalid PID, measurement to be --
    // -- defined.                                                         --
    // --                                                                  --
    // ----------------------------------------------------------------------

    PID_value = PID_boothelper00f;
    PID_result = PID_rcvacn05;

    sendacn_RI_PI_1_ACN04( &PID_value, &PID_result );

    *Framework_Result = TestACNCoverstion_TestACN04;

    if ( PID_result == PID_boothelper00f )
    {
        *Framework_Status = true; // PASS
        if ( PRINT_RESULTS )
        {
            printf( "<TEST_ID> SendACN \n");
            printf("<TEST_RESULT> PASS \n");
        }
    }
    else
    {
        *Framework_Status = false; // FAIL
        if ( PRINT_RESULTS )
        {
            printf("<TEST_ID> SendACN \n");
            printf("<TEST_RESULT> FAIL \n");
            printf("<TEST_FAIL_REASON> TestACNCoverstion_TestACN04 \n");
        }
    }


    // asn1SccPID_Range PID_Range_Value;
    // asn1SccPID_Range PID_Range_result;
    PID_Range_Value = PID_function_18;
    PID_Range_result = 1000;

    sendacn_RI_PI_1_ACN05( &PID_Range_Value , &PID_Range_result  );

    *Framework_Result = TestACNCoverstion_TestACN05;
    if ( PID_Range_result == PID_Range_Value )
    {
        *Framework_Status = true; // PASS
        if ( PRINT_RESULTS )
        {
            printf( "<TEST_ID> SendACN \n");
            printf("<TEST_RESULT> PASS \n");
        }
    }
    else
    {
        *Framework_Status = false; // FAIL
        if ( PRINT_RESULTS )
        {
            printf("<TEST_ID> SendACN \n");
            printf("<TEST_RESULT> FAIL \n");
            printf("<TEST_FAIL_REASON> TestACNCoverstion_TestACN05 \n");
        }
    }

    PID_Range_Value = 1000;     /* this should be an invalid value to test Taste Runtime error handling */
    PID_Range_result = 1000;


    sendacn_RI_PI_1_ACN05( &PID_Range_Value , &PID_Range_result  );

    *Framework_Result = TestACNCoverstion_TestACN05;

    if ( PID_Range_result == PID_Range_Value )
    {
        *Framework_Status = true; // PASS
        if ( PRINT_RESULTS )
        {
            printf( "<TEST_ID> SendACN \n");
            printf("<TEST_RESULT> PASS \n");
        }
    }
    else
    {
        *Framework_Status = false; // FAIL
        if ( PRINT_RESULTS )
        {
            printf("<TEST_ID> SendACN \n");
            printf("<TEST_RESULT> FAIL \n");
            printf("<TEST_FAIL_REASON> TestACNCoverstion_TestACN05 \n");
        }
    }

    // Set the number of test runs that were run
    *Framework_Result = Test_Result;

}



