/* Body file for function SendACN
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "sendacn.h"
#include "limits.h"
//#include <stdio.h>


void sendacn_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[SendACN] Startup");
}

void sendacn_PI_PI_1
        ( asn1SccT_Int32 *Framework_Result, asn1SccT_Boolean *Framework_Status )
{
asn1SccT_Int32 integer_32_value;
asn1SccT_Int32 integer_32_result;
asn1SccT_UInt8 unsigned_08_value;
asn1SccT_UInt8 unsigned_08_result;
asn1SccT_Boolean Boolean_value;
asn1SccT_Boolean Boolean_result;
asn1SccPID PID_value;
asn1SccPID PID_result;
asn1SccPID_Range PID_Range_Value;
asn1SccPID_Range PID_Range_result;
asn1SccT_Int32 Test_Result = 0;

    // A PID is a process Instance Identified or Process ID (PID)
    // Is a number attached to each SDL function or process in the
    // the system.


    // This test shall encode and ecode ACN values
    // between interfaces.
    // ACN parameters of different sizes shall be sent to
    // respectic Receive function, that function shall
    // return the value with a calculation applied
    // to verify correct encode and decode Taste Runtime functions.

    // ---------------------------------------------
    // --                                         --
    // -- 32 bit Integer Tests, ZERO, MAX and MIN --
    // --                                         --
    // ---------------------------------------------

    integer_32_value = 0;
    integer_32_result = INT_MAX;
    Test_Result = 0;                // First Initialisation, this will count
                                    // Sucessful test results
    *Framework_Status = true;       // PASS, any failure will set this to FALSE

    sendacn_RI_PI_1_ACN_01( &integer_32_value , &integer_32_result );
    if ( integer_32_result == 0 )
    {
        Test_Result++;
    }
    else
    {
        *Framework_Status = false; // FAIL
    }

    integer_32_value = INT_MAX;
    integer_32_result = 0;

    sendacn_RI_PI_1_ACN_01( &integer_32_value , &integer_32_result );
    if ( integer_32_result == INT_MAX )
    {
        Test_Result++;
    }
    else
    {
        *Framework_Status = false; // FAIL
    }

    integer_32_value = INT_MIN;
    integer_32_result = 0;

    sendacn_RI_PI_1_ACN_01( &integer_32_value , &integer_32_result );
    if ( integer_32_result == INT_MIN )
    {
        Test_Result++;
    }
    else
    {
        *Framework_Status = false; // FAIL
    }

    // ---------------------------------------------------------------
    // --                                                           --
    // -- Unisigned values are tested for UINT_MAX and UINT_MIN (0) --
    // --                                                           --
    // ---------------------------------------------------------------

    unsigned_08_value = 0;
    unsigned_08_result = UCHAR_MAX;
    sendacn_RI_PI_1_ACN_02( &unsigned_08_value, &unsigned_08_result );
    if ( unsigned_08_result == 0 )
    {
         Test_Result++;       // This return with a value representing
                              // the number of tests that passed
    }
    else
    {
         *Framework_Status = false; // FAIL
    }

    unsigned_08_value = UCHAR_MAX;
    unsigned_08_result = 0;
    sendacn_RI_PI_1_ACN_02( &unsigned_08_value, &unsigned_08_result );
    if ( unsigned_08_result == UCHAR_MAX )
    {
        Test_Result++;       // This return with a value representing
                             // the number of tests that passed
    }
    else
    {
        *Framework_Status = false; // FAIL
    }

    // --------------------------------------------------
    // --                                              --
    // -- Boolean values are tested for True and False --
    // --                                              --
    // --------------------------------------------------

    Boolean_value = true;
    Boolean_result = false;
    // extern void sendacn_RI_PI_1_ACN03( const asn1SccT_Boolean *, asn1SccT_Boolean * );

    sendacn_RI_PI_1_ACN03( &Boolean_value , &Boolean_result );
    if ( Boolean_result == true )
    {
        Test_Result++;       // This return with a value representing
                             // the number of tests that passed
    }
    else
    {
        *Framework_Status = false; // FAIL
    }

    Boolean_value = false;
    Boolean_result = true;

    sendacn_RI_PI_1_ACN03( &Boolean_value , &Boolean_result );
    if ( Boolean_result == false )
    {
        Test_Result++;      // This return with a value representing
                            // the number of tests that passed
    }
    else
    {
        *Framework_Status = false; // FAIL
    }

    // ----------------------------------------------------------------------
    // --                                                                  --
    // -- PID Process Instance Identified or Process ID                    --
    // -- Taste Builds a list of PID's based on the function               --
    // -- names in a list identified from 0..n, which is regenerated       --
    // -- everybuild within "dataview-uniq.h" enum type "asn1SccPID"       --
    // -- Macros are defined for each enumeration.                         --
    // --                                                                  --
    // -- This test will test min "asn1SccPID_boothelper00f" to "PID_env"  --
    // -- This test will attempt to test an invalid PID, measurement to be --
    // -- defined.                                                         --
    // --                                                                  --
    // ----------------------------------------------------------------------

    PID_value = PID_boothelper00f;
    PID_result = PID_rcvacn05;

    sendacn_RI_PI_1_ACN04( &PID_value, &PID_result );
    if ( PID_result == PID_boothelper00f )
    {
        Test_Result++;       // This return with a value representing
                             // the number of tests that passed
    }
    else
    {
        *Framework_Status = false; // FAIL
    }

    PID_value = PID_env;
    PID_result = PID_boothelper00f;

    sendacn_RI_PI_1_ACN04( &PID_value, &PID_result );
    if ( PID_result == PID_env )
    {
        Test_Result++;      // This return with a value representing
                            // the number of tests that passed
    }
    else
    {
        *Framework_Status = false; // FAIL
    }


    PID_Range_Value = PID_boothelper00f;
    PID_Range_result = 1000;

    //sendacn_RI_PI_1_ACN05( const asn1SccPID_Range *, asn1SccPID_Range * );
    sendacn_RI_PI_1_ACN05( &PID_Range_Value , &PID_Range_result  );
    if ( PID_Range_result == PID_Range_Value )
    {

        Test_Result++;      // This return with a value representing
                            // the number of tests that passed

    }
    else
    {
        *Framework_Status = false; // FAIL
    }

    PID_Range_Value = 1000;     /* this should be an invalid value */
    PID_Range_result = 0;

    //sendacn_RI_PI_1_ACN05( const asn1SccPID_Range *, asn1SccPID_Range * );
    sendacn_RI_PI_1_ACN05( &PID_Range_Value , &PID_Range_result  );
    if ( PID_Range_result == PID_Range_Value )
    {

        Test_Result++;      // This return with a value representing
                            // the number of tests that passed

    }
    else
    {
        *Framework_Status = false; // FAIL
    }

    // Set the number of test runs that were run
    *Framework_Result = Test_Result;

}



