/* Body file for function Sender011
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "sender011.h"
#include "../../../../test_defines.h"           // Custom include, NOT managed by TASTE
#include <stdio.h>


void sender011_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[Sender011] Startup");
}


/************************************************************
 * <Test ID>
 * <Sender011>
 * <Purpose>
 * This test calls 10 receive functions, using unprotected interfaces.
 * <Requirements>
 *  - MBEP-RT-FUN-80
 *  - MBEP-RT-FUN-210
 *  - MBEP-RT-FUN-211
 *  - MBEP-RT-FUN-231
 * <inputs specification>
 * <outputs specification>
 * <Procedure: Proceed steps>
 * - Set up Parameters
 * Call 10 functions using Protected Interfaces from a single send interface
 * in order to meet above requirements, varying values sent to functions, which
 * report the value received and set a true or false status.
 *<Test failure>
 * - Test will fail if any functions call fails to complete, returning
 *   execution to the testfunction.
 * - Test will fail if the passed parameter is incorrect.
 *   The Receiver function validates the known passed parameter.
 *************************************************************/

void sender011_PI_PI_1_Start_Send_Tests( asn1SccT_Int32 *OUT_p1, asn1SccT_Boolean *OUT_p2 )
{
asn1SccT_Int32 Parameter_N = 0;
asn1SccT_Boolean test_status = false;


    // --
    // -- Receiver Function11 to Function20, each function interface is SRnn
    // --

    Parameter_N = 1000;
    sender011_RI_PI_1_SR11( &Parameter_N, &test_status );


    *OUT_p1 = TestCOMMS10_SR11_Communication_Test;
    if ( test_status == false )
    {
        *OUT_p2 = true;
        if ( PRINT_RESULTS )
        {
            printf( "<TEST_ID> Sender011\n");
            printf("<TEST_RESULT> PASS \n");
        }
    }
    else
    {
        *OUT_p2 = false;
        if ( PRINT_RESULTS )
        {
            printf("<TEST_ID> Sender011 \n");
            printf("<TEST_RESULT> FAIL \n");
            printf("<TEST_FAIL_REASON> TestCOMMS10_SR11_Communication_Test \n");
        }
    }

    Parameter_N = 900;
    sender011_RI_PI_1_SR12( &Parameter_N, &test_status );


    *OUT_p1 = TestCOMMS10_SR12_Communication_Test;
    if ( test_status == false )
    {
        *OUT_p2 = true;
        if ( PRINT_RESULTS )
        {
            printf( "<TEST_ID> Sender012\n");
            printf("<TEST_RESULT> PASS \n");
        }
        else
        {
            *OUT_p2 = false;
            if ( PRINT_RESULTS )
            {
                printf("<TEST_ID> Sender012 \n");
                printf("<TEST_RESULT> FAIL \n");
                printf("<TEST_FAIL_REASON> TestCOMMS10_SR12_Communication_Test \n");
            }
        }
    }

    // No clue why Taste won't make the call sender011_RI_Receiver_PI_1
    // tried several times...
    Parameter_N = 800;
    sender011_RI_PI_1_SR13( &Parameter_N, &test_status );


    *OUT_p1 = TestCOMMS10_SR13_Communication_Test;
    if ( test_status == false )
    {
        *OUT_p2 = true;
        if ( PRINT_RESULTS )
        {
            printf("<TEST_ID> Sender013\n");
            printf("<TEST_RESULT> PASS \n");
        }
        else
        {
            *OUT_p2 = false;
            if ( PRINT_RESULTS )
            {
                printf("<TEST_ID> Sender013 \n");
                printf("<TEST_RESULT> FAIL \n");
                printf("<TEST_FAIL_REASON> TestCOMMS10_SR13_Communication_Test \n");
            }
        }
    }

    Parameter_N = 700;
    sender011_RI_PI_1_SR14( &Parameter_N, &test_status );

    *OUT_p1 = TestCOMMS10_SR14_Communication_Test;
    if ( test_status == false )
    {
        *OUT_p2 = true;
        if ( PRINT_RESULTS )
        {
            printf("<TEST_ID> Sender014\n");
            printf("<TEST_RESULT> PASS \n");
        }
        else
        {
            *OUT_p2 = false;
            if ( PRINT_RESULTS )
            {
                printf("<TEST_ID> Sender014 \n");
                printf("<TEST_RESULT> FAIL \n");
                printf("<TEST_FAIL_REASON> TestCOMMS10_SR14_Communication_Test \n");
            }
        }
    }

    Parameter_N = 600;
    sender011_RI_PI_1_SR15( &Parameter_N, &test_status );

    *OUT_p1 = TestCOMMS10_SR15_Communication_Test;
    if ( test_status == false )
    {
        *OUT_p2 = true;
        if ( PRINT_RESULTS )
        {
            printf("<TEST_ID> Sender015\n");
            printf("<TEST_RESULT> PASS \n");
        }
        else
        {
            *OUT_p2 = false;
            if ( PRINT_RESULTS )
            {
                printf("<TEST_ID> Sender015 \n");
                printf("<TEST_RESULT> FAIL \n");
                printf("<TEST_FAIL_REASON> TestCOMMS10_SR15_Communication_Test \n");
            }
        }
    }

    Parameter_N = 500;
    sender011_RI_PI_1_SR16( &Parameter_N, &test_status );

    *OUT_p1 = TestCOMMS10_SR16_Communication_Test;
    if ( test_status == false )
    {
        *OUT_p2 = true;
        if ( PRINT_RESULTS )
        {
            printf("<TEST_ID> Sender016\n");
            printf("<TEST_RESULT> PASS \n");
        }
        else
        {
            *OUT_p2 = false;
            if ( PRINT_RESULTS )
            {
                printf("<TEST_ID> Sender016 \n");
                printf("<TEST_RESULT> FAIL \n");
                printf("<TEST_FAIL_REASON> TestCOMMS10_SR16_Communication_Test \n");
            }
        }
    }

    Parameter_N = 400;
    sender011_RI_PI_1_SR17( &Parameter_N, &test_status );

    *OUT_p1 = TestCOMMS10_SR17_Communication_Test;
    if ( test_status == false )
    {
        *OUT_p2 = true;
        if ( PRINT_RESULTS )
        {
            printf("<TEST_ID> Sender017\n");
            printf("<TEST_RESULT> PASS \n");
        }
        else
        {
            *OUT_p2 = false;
            if ( PRINT_RESULTS )
            {
                printf("<TEST_ID> Sender017 \n");
                printf("<TEST_RESULT> FAIL \n");
                printf("<TEST_FAIL_REASON> TestCOMMS10_SR17_Communication_Test \n");
            }
        }
    }

    Parameter_N = 300;
    sender011_RI_PI_1_SR18( &Parameter_N, &test_status );
    if ( test_status == false )

    *OUT_p1 = TestCOMMS10_SR18_Communication_Test;
    if ( test_status == false )
    {
        *OUT_p2 = true;
        if ( PRINT_RESULTS )
        {
            printf("<TEST_ID> Sender018\n");
            printf("<TEST_RESULT> PASS \n");
        }
        else
        {
            *OUT_p2 = false;
            if ( PRINT_RESULTS )
            {
                printf("<TEST_ID> Sender018 \n");
                printf("<TEST_RESULT> FAIL \n");
                printf("<TEST_FAIL_REASON> TestCOMMS10_SR18_Communication_Test \n");
            }
        }
    }
    Parameter_N = 200;
    sender011_RI_PI_1_SR19( &Parameter_N, &test_status );

    *OUT_p1 = TestCOMMS10_SR19_Communication_Test;
    if ( test_status == false )
    {
        *OUT_p2 = true;
        if ( PRINT_RESULTS )
        {
            printf("<TEST_ID> Sender019\n");
            printf("<TEST_RESULT> PASS \n");
        }
        else
        {
            *OUT_p2 = false;
            if ( PRINT_RESULTS )
            {
                printf("<TEST_ID> Sender019 \n");
                printf("<TEST_RESULT> FAIL \n");
                printf("<TEST_FAIL_REASON> TestCOMMS10_SR19_Communication_Test \n");
            }
        }
    }

    Parameter_N = 100;
    sender011_RI_PI_1_SR20( &Parameter_N, &test_status );

    *OUT_p1 = TestCOMMS10_SR20_Communication_Test;
    if ( test_status == false )
    {
        *OUT_p2 = true;
        if ( PRINT_RESULTS )
        {
            printf("<TEST_ID> Sender020\n");
            printf("<TEST_RESULT> PASS \n");
        }
        else
        {
            *OUT_p2 = false;
            if ( PRINT_RESULTS )
            {
                printf("<TEST_ID> Sender020 \n");
                printf("<TEST_RESULT> FAIL \n");
                printf("<TEST_FAIL_REASON> TestCOMMS10_SR20_Communication_Test \n");
            }
        }
    }
}


