/* Header file for function Sender003
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void sender003_startup(void);

/* Provided interfaces */
void sender003_PI_PI_1_Send03( asn1SccT_Int32 *, asn1SccT_Boolean * );

/* Required interfaces */
extern void sender003_RI_PI_3( const asn1SccT_Int32 *, asn1SccT_Boolean * );


#ifdef __cplusplus
}
#endif
