/* Header file for function TestModules
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void testmodules_startup(void);

/* Provided interfaces */
void testmodules_PI_PI_10_TestModules( asn1SccT_Int32 *, asn1SccT_Boolean * );

/* Required interfaces */
extern void testmodules_RI_PI_1_ActivationLog( asn1SccT_Int32 *, asn1SccT_Boolean * );


extern void testmodules_RI_PI_1_Boot_Helper( asn1SccT_Int32 *, asn1SccT_Boolean * );


extern void testmodules_RI_PI_1_BrokerLog( asn1SccT_Int32 *, asn1SccT_Boolean * );


extern void testmodules_RI_PI_1_CPUCore( asn1SccT_Int32 *, asn1SccT_Boolean * );


extern void testmodules_RI_PI_1_DeathReport( asn1SccT_Int32 *, asn1SccT_Boolean * );


extern void testmodules_RI_PI_1_HAL( asn1SccT_Int32 *, asn1SccT_Boolean * );


extern void testmodules_RI_PI_1_MonCallback( asn1SccT_Int32 *, asn1SccT_Boolean * );


extern void testmodules_RI_PI_1_Threads( asn1SccT_Int32 *, asn1SccT_Boolean * );


extern void testmodules_RI_PI_2_Mon00A( asn1SccT_Int32 *, asn1SccT_Boolean * );


#ifdef __cplusplus
}
#endif
