/* Body file for function trigger_logging
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "trigger_logging.h"


void trigger_logging_startup(void)
{
}

void trigger_logging_PI_trigger1(void)
{
    trigger_logging_RI_sporadic_if();
}


