/* Header file for function TestUnProt00
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void testunprot00_startup(void);

/* Provided interfaces */
void testunprot00_PI_PI_1_00( void );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
