/* Body file for function TestUnProt00
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "testunprot00.h"
//#include <stdio.h>


void testunprot00_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[TestUnProt00] Startup");
}

void testunprot00_PI_PI_1_00(void)
{
    // -- This absolutely nothing, protected interface
    // -- with no parameters.
    // -- MBEP-RT-FUN-170
}


