#!/usr/bin/env python3

#  Automatically generated by kazoo/templates/glue/language_wrappers/mini-cv-python
#  DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
#  This is an input file for the DMT tool "aadl2glueC". It is imported
#  at runtime and its role is to populate DMT's AST prior to executing the
#  B mapper functions.

from dmt.commonPy import aadlAST as ast

ast.g_apLevelContainers = dict()

# Interface "PI_1"
sp = ast.ApLevelContainer("PI_1")
ast.g_apLevelContainers["PI_1"] = sp

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::Interface_Cyclic_Offset = 0
# Taste::Interface_Priority = 1
# Taste::Interface_Stack_Size = 50
# Taste::InterfaceName = PI_1
# Taste::RCMoperationKind = cyclic
# Taste::RCMperiod = 100 ms
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = C
ast.g_subProgramImplementations.append(["PI_1", "C", "C", "testcyclic05", sp._fpgaConfigurations])
sp._language = "C"


# Interface "PI_2"
sp = ast.ApLevelContainer("PI_2")
ast.g_apLevelContainers["PI_2"] = sp
subProgramParameters = []
param = ast.AadlParameter("IN", "DataView::T_Int32")
param._encoding = "NATIVE"
subProgramFeature = ast.AadlSubProgramFeature("p1", param)
subProgramParameters.append(subProgramFeature)
for spFeature in subProgramParameters:
    if spFeature is None: continue
    param_type = "T_Int32"
    signal = ast.g_signals[param_type]
    if spFeature._parameter._direction == "IN":
        param = ast.InParam("PI_2", "p1", signal, spFeature._parameter)
    elif spFeature._parameter._direction == "OUT":
        param = ast.OutParam("PI_2", "p1", signal, spFeature._parameter)
    sp.AddParam(param)

# Compute_Execution_Time = 0ms..0ms
# Taste::Communication_Layer = default
# Taste::InterfaceName = PI_2
# Taste::RCMoperationKind = unprotected
sp._fpgaConfigurations = ""   # initialization
# Taste::Instances_Max = 1
# Taste::Instances_Min = 1
# Taste::Startup_Priority = 1
# TASTE_IV_Properties::Default_Codegen = C
ast.g_subProgramImplementations.append(["PI_2", "C", "C", "testcyclic05", sp._fpgaConfigurations])
sp._language = "C"



