/* Body file for function test_sdl_timer
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "test_sdl_timer.h"
#include <stdio.h>
#include <Hal.h>
#include "../../../../../tf_common/tf_uart_comms.h"
#include "../../../../../tf_common/tf_test_results.h"

static bool bResultReported = false;
static int iNumberOfInvocations = 0;


// Constructor
void test_sdl_timer_startup(void)
{
    // Register the test that this TASTE Function will submit a result for
    testresult_register_test(TF_TEST_ID__TestSdlToAda);
}


// Handler calls from the SDL function
void test_sdl_timer_PI_protected_if(const asn1SccMyInteger *IN_counter)
{
    // Increment count of invocations
    iNumberOfInvocations++;
}


// Determine pass/fail and submit the test result to the TASTE test framework
void test_sdl_timer_PI_trigger_check(void)
{
    // Skip this if we already reported a result
    if (bResultReported)
    {
        return;
    }

    // Submit the test result
    if (iNumberOfInvocations > 1)
    {
        testresult_report_pass(TF_TEST_ID__TestSdlToAda);
    } else {
        testresult_report_fail(TF_TEST_ID__TestSdlTimer, "Did not receive any invocations from the Ada function in the exppecte timeframe");
    }

    // Only report the result once
    bResultReported = true;
}
