/* Body file for function Function_4
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "function_4_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void function_4_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void CInitfunction_4(void);

unsigned function_4_initialized = 0;
void init_function_4(void)
{
   if (0 == function_4_initialized) {
      function_4_initialized = 1;
      // Call user code startup function
      extern void function_4_startup(void);
      function_4_startup();
      function_4_initialized = 2;
   }
}
void function_4_PI_4
      (const char *IN_p1, size_t IN_p1_len)

{
   sender_pid = function_4_pi_4_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void function_4_PI_PI_4
      (const asn1SccT_Int32 *);





   // Call user code
   function_4_PI_PI_4 ((asn1SccT_Int32 *)IN_p1);

}




void function_4_PI_cyclic_4(void)
{

   //  Directly call user code, no parameters to pass
   extern void function_4_PI_PI_cyclic_4(void);
   function_4_PI_PI_cyclic_4();
   // puts ("function_4_pi_cyclic_4 called");
}

