/* Body file for function Function_1
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "function_1.h"
#include <DeathReport.h>

/*
 * =============================
 * DEATH REPORT PERSISTENCE
 * =============================
 *
 * This model can be yused to demonstrate death report persistence:
 *
 * 1. Build
 * 2. Start gdb client (with server on alpaca)
 * 3. Commands:
 *       monitor reset
 *       load
 *       break function_1.c:53
 *       c
 * 4. On first hit of the breakpoint, command:
 *       display death_report->checksum
 *       c
 * 5. On each next hit of the breakpoint the rendered checksum should increase by 50.
 *
 * 6. THEN! Reset:
 *       monitor reset
 *       load
 *       c
 *
 * 7. When gdb now halts at the breakkpoint, the SAME previous checkum value should be seen rendered
 */


extern const uint32_t DEATH_REPORT_BEGIN;


void function_1_startup(void)
{
}

void function_1_PI_trigger(void)
{
    DeathReportWriter_DeathReport *const death_report = (DeathReportWriter_DeathReport *const)&DEATH_REPORT_BEGIN;

    // Update the checksum
    if (death_report->checksum > 1000) {
        death_report->checksum = 50;
    } else {
        death_report->checksum = death_report->checksum + 50;
    }
}


