/* Body file for function Sender001
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "sender001_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void sender001_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void CInitsender001(void);

extern void init_receiver001(void);
extern unsigned receiver001_initialized;
unsigned sender001_initialized = 0;
void init_sender001(void)
{
   if (0 == sender001_initialized) {
      sender001_initialized = 1;
      // Call user code startup function
      extern void sender001_startup(void);
      sender001_startup();
      // Iterate over all synchronous RIs, and call their parent's
      // init function. Multiple calls are prevented by the "init" guard.
      if (0 == receiver001_initialized) {
          init_receiver001();
      }
      sender001_initialized = 2;
   }
}
void sender001_PI_1_Send01
      (char *OUT_p1, size_t *OUT_p1_len,
       char *OUT_p2, size_t *OUT_p2_len)

{
   sender_pid = sender001_pi_1_send01_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void sender001_PI_PI_1_Send01
      (asn1SccT_Int32 *,
       asn1SccT_Boolean *);





   // Call user code
   sender001_PI_PI_1_Send01 ((asn1SccT_Int32 *)OUT_p1, (asn1SccT_Boolean *)OUT_p2);

}

