/* Header file for function UartOtherEnd
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void uartotherend_startup(void);

/* Provided interfaces */
void uartotherend_PI_uart1tx( const asn1SccT_UInt8 * );


void uartotherend_PI_uart3tx( const asn1SccT_UInt8 * );

/* Required interfaces */
extern void uartotherend_RI_uart1rx( const asn1SccT_UInt8 * );


extern void uartotherend_RI_uart3rx( const asn1SccT_UInt8 * );


#ifdef __cplusplus
}
#endif
