/* Body file for function TestUnProtected
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "testunprotected_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void testunprotected_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void CInittestunprotected(void);

extern void init_testunprot00(void);
extern unsigned testunprot00_initialized;
extern void init_testunprotin05(void);
extern unsigned testunprotin05_initialized;
extern void init_testunprotout05(void);
extern unsigned testunprotout05_initialized;
unsigned testunprotected_initialized = 0;
void init_testunprotected(void)
{
   if (0 == testunprotected_initialized) {
      testunprotected_initialized = 1;
      // Call user code startup function
      extern void testunprotected_startup(void);
      testunprotected_startup();
      // Iterate over all synchronous RIs, and call their parent's
      // init function. Multiple calls are prevented by the "init" guard.
      if (0 == testunprot00_initialized) {
          init_testunprot00();
      }
      if (0 == testunprotin05_initialized) {
          init_testunprotin05();
      }
      if (0 == testunprotout05_initialized) {
          init_testunprotout05();
      }
      testunprotected_initialized = 2;
   }
}
void testunprotected_PI_1_UnProt_Start
      (char *OUT_p1, size_t *OUT_p1_len,
       char *OUT_p2, size_t *OUT_p2_len)

{
   sender_pid = testunprotected_pi_1_unprot_start_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void testunprotected_PI_PI_1_UnProt_Start
      (asn1SccT_Int32 *,
       asn1SccT_Boolean *);





   // Call user code
   testunprotected_PI_PI_1_UnProt_Start ((asn1SccT_Int32 *)OUT_p1, (asn1SccT_Boolean *)OUT_p2);

}

