/* Body file for function stack_user_2
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "stack_user_2.h"
//#include <stdio.h>


void stack_user_2_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[stack_user_2] Startup");
}

void stack_user_2_PI_tested_thread_2(void)
{
   // Write your code here
}


