/* Body file for function Function_2
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "function_2.h"
//#include <stdio.h>


void function_2_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[Function_2] Startup");
}

//
// Note, this function is being called only to prove
//       both cyclic and spradic interfaces
//
void function_2_PI_PI_cyclic_2( void )
{
int counter = 0;

    // This is a mandatory cycle interface, which will
    // be received, a counter will be implemented
    if ( counter > 2147483000 )
    {
        counter = 0;
    }

    counter++;
}


//
// function_2_PI_PI_2 receives a message from function_1_PI_PI_1
//
void function_2_PI_PI_2( const asn1SccT_Int32 * data_in )
{
    asn1SccT_Int32 data = 0;

    data = *data_in + 1;
    // Send the data to the next function (3)
    function_2_RI_PI_3( &data );

}

