/* Body file for function TestSDL08
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "testsdl08_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void testsdl08_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void CInittestsdl08(void);

extern void init_partition_1_timer_manager(void);
extern unsigned partition_1_timer_manager_initialized;
unsigned testsdl08_initialized = 0;
void init_testsdl08(void)
{
   if (0 == testsdl08_initialized) {
      testsdl08_initialized = 1;
      // Initialize C to call elaboration functions
      CInittestsdl08();
      // Iterate over all synchronous RIs, and call their parent's
      // init function. Multiple calls are prevented by the "init" guard.
      if (0 == partition_1_timer_manager_initialized) {
          init_partition_1_timer_manager();
      }
      testsdl08_initialized = 2;
   }
}
void testsdl08_PI_STARTSDL08
      (const char *IN_p1, size_t IN_p1_len)

{
   sender_pid = testsdl08_pi_startsdl08_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void testsdl08_PI_PI_STARTSDL08
      (const asn1SccCounter *);





   // Call user code
   testsdl08_PI_PI_STARTSDL08 ((asn1SccCounter *)IN_p1);

}




void testsdl08_mytime(void)
{
   sender_pid = testsdl08_mytime_get_sender();

   //  Directly call user code, no parameters to pass
   extern void testsdl08_PI_mytime(void);
   testsdl08_PI_mytime();
   // puts ("testsdl08_mytime called");
}

