/* Body file for function test_priority
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "test_priority.h"
#include "../../../../../tf_common/tf_uart_comms.h"
#include "../../../../../tf_common/tf_test_results.h"
#include <stdio.h>
#include "interfaces_info.h"
#include <rtems.h>

// The priorities configured in the interface for Sporadic and Cyclic interfaces
#define SPORADIC_IF_1_PRIORITY  5
#define SPORADIC_IF_2_PRIORITY  12
#define CYCLIC_IF_1_PRIORITY    5
#define CYCLIC_IF_2_PRIORITY    13

// Constructor
void test_priority_startup(void)
{
    // Register the test that this TASTE Function will submit a result for
    testresult_register_test(TF_TEST_ID__TestPriority);
}



// Determine pass/fail and submit result over UART
void test_priority_PI_trigger_check(void)
{
    char aMsgBuff[100];
    bool bStatus = true;
    rtems_id iSchedulerId;
    rtems_task_priority iPriority_SpIf1;
    rtems_task_priority iPriority_SpIf2;
    rtems_task_priority iPriority_CyIf1;
    rtems_task_priority iPriority_CyIf2;

    // Read in the various priority values from the OS
    bStatus = bStatus && (rtems_task_get_scheduler(RTEMS_SELF, &iSchedulerId) == RTEMS_SUCCESSFUL);
    bStatus = bStatus && (rtems_task_get_priority(threads_info[test_priority_sporadic_if_1].id, iSchedulerId, &iPriority_SpIf1) == RTEMS_SUCCESSFUL);
    bStatus = bStatus && (rtems_task_get_priority(threads_info[test_priority_sporadic_if_2].id, iSchedulerId, &iPriority_SpIf2) == RTEMS_SUCCESSFUL);
    bStatus = bStatus && (rtems_task_get_priority(threads_info[test_priority_cyclic_if_1].id, iSchedulerId, &iPriority_CyIf1) == RTEMS_SUCCESSFUL);
    bStatus = bStatus && (rtems_task_get_priority(threads_info[test_priority_cyclic_if_2].id, iSchedulerId, &iPriority_CyIf2) == RTEMS_SUCCESSFUL);


    // Was reading any of these data unsuccessful?
    if (!bStatus)
    {
        testresult_report_fail(TF_TEST_ID__TestPriority, "One or more RTEMS function calls gave a failure response");
    }

    // SP IF 1 priority not as expected?
    else if (iPriority_SpIf1 != SPORADIC_IF_1_PRIORITY)
    {
        sprintf(aMsgBuff, "Priority of sporadic_if_1 not %i as expected but rather %i", SPORADIC_IF_1_PRIORITY, iPriority_SpIf1);
        testresult_report_fail(TF_TEST_ID__TestPriority, aMsgBuff);
    }

    // SP IF 2 priority not as expected?
    else if (iPriority_SpIf2 != SPORADIC_IF_2_PRIORITY)
    {
        sprintf(aMsgBuff, "Priority of sporadic_if_2 not %i as expected but rather %i", SPORADIC_IF_2_PRIORITY, iPriority_SpIf2);
        testresult_report_fail(TF_TEST_ID__TestPriority, aMsgBuff);
    }

    // Cyclic IF 1 priority not as expected?
    else if (iPriority_CyIf1 != CYCLIC_IF_1_PRIORITY)
    {
        sprintf(aMsgBuff, "Priority of cyclic_if_1 not %i as expected but rather %i", CYCLIC_IF_1_PRIORITY, iPriority_CyIf1);
        testresult_report_fail(TF_TEST_ID__TestPriority, aMsgBuff);
    }

    // Cyclic IF 2 priority not as expected?
    else if (iPriority_CyIf2 != CYCLIC_IF_2_PRIORITY)
    {
        sprintf(aMsgBuff, "Priority of cyclic_if_2 not %i as expected but rather %i", CYCLIC_IF_2_PRIORITY, iPriority_CyIf2);
        testresult_report_fail(TF_TEST_ID__TestPriority, aMsgBuff);
    }

    // Else its a pass
    else
    {
        testresult_report_pass(TF_TEST_ID__TestPriority);
    }
}


// Handler for sporadic_if_1 IF
void test_priority_PI_sporadic_if_1(void)
{
    asm volatile("nop");
}


// Handler for sporadic_if_2 IF
void test_priority_PI_sporadic_if_2(void)
{
    asm volatile("nop");
}


// Handler for cyclic_if_1 IF
void test_priority_PI_cyclic_if_1(void)
{
    asm volatile("nop");
}


// Handler for cyclic_if_2 IF
void test_priority_PI_cyclic_if_2(void)
{
    asm volatile("nop");
}

