/* Header file for function TestProt04
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void testprot04_startup(void);

/* Provided interfaces */
void testprot04_PI_PI_1( const asn1SccT_Int32 *, asn1SccT_Boolean * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
