/* Header file for function testfunction
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm_if-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

/* The purpose of this file is to provide a wrapper around the user code,
 * with a single interface that is independent of the implementation language
 * of the function. The parameters of each PI are blackboxes encoded
 * in the form specified in the interface view (Native, uPER, or ACN)
*/

#pragma once
#if defined(__unix__) || defined (__MSP430__)
   #include <stdlib.h>
   #include <stdio.h>
#else
   typedef unsigned size_t;
#endif

#include "C_ASN1_Types.h"
#ifdef __cplusplus
extern "C" {
#endif

#include "testfunction.h"

// Function initialization - calls user startup code of all dependent functions
void init_testfunction(void);


/* Provided interfaces */
void testfunction_PI_1
      (const char *IN_p1, size_t IN_p1_len);



void testfunction_PI_2
      (const char *IN_p1, size_t IN_p1_len);



void testfunction_PI_3
      (const char *IN_p1, size_t IN_p1_len);



void testfunction_PI_4
      (const char *IN_p1, size_t IN_p1_len);



void testfunction_PI_5
      (const char *IN_p1, size_t IN_p1_len);



void testfunction_PI_6
      (const char *IN_p1, size_t IN_p1_len);



void testfunction_PI_7
      (const char *IN_p1, size_t IN_p1_len);



void testfunction_PI_8
      (const char *IN_p1, size_t IN_p1_len);



void testfunction_trigger_check(void);


#ifdef __cplusplus
}
#endif

