/* Body file for function Prot00IF
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "prot00if_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void prot00if_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void CInitprot00if(void);

unsigned prot00if_initialized = 0;
void init_prot00if(void)
{
   if (0 == prot00if_initialized) {
      prot00if_initialized = 1;
      // Call user code startup function
      extern void prot00if_startup(void);
      prot00if_startup();
      prot00if_initialized = 2;
   }
}
void prot00if_PI_1_ZERO(void)
{
   sender_pid = prot00if_pi_1_zero_get_sender();

   //  Directly call user code, no parameters to pass
   extern void prot00if_PI_PI_1_ZERO(void);
   prot00if_PI_PI_1_ZERO();
   // puts ("prot00if_pi_1_zero called");
}

