/* Body file for function DeathReport00C
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "deathreport00c_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void deathreport00c_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void CInitdeathreport00c(void);

unsigned deathreport00c_initialized = 0;
void init_deathreport00c(void)
{
   if (0 == deathreport00c_initialized) {
      deathreport00c_initialized = 1;
      // Call user code startup function
      extern void deathreport00c_startup(void);
      deathreport00c_startup();
      deathreport00c_initialized = 2;
   }
}
void deathreport00c_PI_1_DeathReport
      (char *OUT_p1, size_t *OUT_p1_len,
       char *OUT_p2, size_t *OUT_p2_len)

{
   sender_pid = deathreport00c_pi_1_deathreport_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void deathreport00c_PI_PI_1_DeathReport
      (asn1SccT_Int32 *,
       asn1SccT_Boolean *);





   // Call user code
   deathreport00c_PI_PI_1_DeathReport ((asn1SccT_Int32 *)OUT_p1, (asn1SccT_Boolean *)OUT_p2);

}

