/* Body file for function test_encoding_errors
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "test_encoding_errors.h"
#include "../../../../../tf_common/tf_uart_comms.h"
#include "../../../../../tf_common/tf_test_results.h"
#include <stdio.h>


// There is an auto-generated function for this object that we will need to acess in this test. Declare it here.
void test_encoding_errors_RI_get_last_error(asn1SccT_Runtime_Error* err);

// Flag to ensure we only report the test result at most once
static asn1SccT_Boolean bResultReported = false;

#define EXPECTED_ERROR_KIND T_Runtime_Error_encodeerror_PRESENT
#define EXPECTED_ENCODING_ERROR ERR_MYINTEGERWITHLIMITEDRANGE


// Constructor
void test_encoding_errors_startup(void)
{
    // Register the test that this TASTE Function will submit a result for
    testresult_register_test(TF_TEST_ID__TestEncodingErrors);
}


void test_encoding_errors_PI_trigger_check()
{
    char aFailureMsg[100];

    // Only do this once
    if (bResultReported)
    {
        return;
    }

    // Pass a too-large value into the required interface
    asn1SccMyIntegerWithLimitedRange var = 400;
    test_encoding_errors_RI_sporadic_if(&var);

    // Call our "get_last_error" function to check for encoding errors
    asn1SccT_Runtime_Error err;
    err.kind = T_Runtime_Error_noerror_PRESENT;
    test_encoding_errors_RI_get_last_error(&err);

    // Did we not get the expected error kind?
    if (err.kind != EXPECTED_ERROR_KIND)
    {
        sprintf(aFailureMsg, "Did not get the expected error kind (%i) but rather %i", err.kind, EXPECTED_ERROR_KIND);
        testresult_report_fail(TF_TEST_ID__TestEncodingErrors, aFailureMsg);
    }

    // Did we not get the expected encoding error?
    else if (err.u.encodeerror != EXPECTED_ENCODING_ERROR)
    {
        sprintf(aFailureMsg, "Did not get the expected encoding error (%i) but rather %i", err.u.encodeerror, EXPECTED_ENCODING_ERROR);
        testresult_report_fail(TF_TEST_ID__TestEncodingErrors, aFailureMsg);
    }
    else
    {
        testresult_report_pass(TF_TEST_ID__TestEncodingErrors);
    }

    // Report that we already did this
    bResultReported = true;
}



