/* Header file for function Sender001
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void sender001_startup(void);

/* Provided interfaces */
void sender001_PI_PI_1_Cyclic( void );


void sender001_PI_PI_2( const asn1SccT_Int32 * );

/* Required interfaces */
extern void sender001_RI_PI_1( const asn1SccT_Int32 * );


#ifdef __cplusplus
}
#endif
