/* Header file for function TestUnProtIN05
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void testunprotin05_startup(void);

/* Provided interfaces */
void testunprotin05_PI_PI_1( const asn1SccT_Int32 *, const asn1SccT_UInt32 *, const asn1SccT_Int8 *, const asn1SccT_UInt8 *, const asn1SccT_Boolean *, asn1SccT_Boolean * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
