/* Body file for function TestUnProt00
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "testunprot00_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void testunprot00_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void CInittestunprot00(void);

unsigned testunprot00_initialized = 0;
void init_testunprot00(void)
{
   if (0 == testunprot00_initialized) {
      testunprot00_initialized = 1;
      // Call user code startup function
      extern void testunprot00_startup(void);
      testunprot00_startup();
      testunprot00_initialized = 2;
   }
}
void testunprot00_PI_1_00(void)
{
   sender_pid = testunprot00_pi_1_00_get_sender();

   //  Directly call user code, no parameters to pass
   extern void testunprot00_PI_PI_1_00(void);
   testunprot00_PI_PI_1_00();
   // puts ("testunprot00_pi_1_00 called");
}

