/* Body file for function test_fpu
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "test_fpu.h"
#include "../../../../../tf_common/tf_uart_comms.h"
#include "../../../../../tf_common/tf_test_results.h"
#include "../../../../../tf_common/tf_cpu.h"
#include <stdio.h>


// Flag to ensure we only report the test result at most once
static asn1SccT_Boolean bResultReported = false;


// Constructor
void test_fpu_startup(void)
{
    // Register the test that this TASTE Function will submit a result for
    testresult_register_test(TF_TEST_ID__TestFpu);
}


// Handler for cyclic IF: Validates that FPU is enabled
void test_fpu_PI_trigger_check(void)
{
    // Only do this once
    if (bResultReported) {
        return;
    }

    // Determine whether the FPU is currently enabled
    if (is_fpu_enabled())
    {
        testresult_report_pass(TF_TEST_ID__TestFpu);
    }
    else
    {
        testresult_report_fail(TF_TEST_ID__TestFpu, "FPU is not enabled");
    }

    // Report that we already did this
    bResultReported = true;
}


