/* Body file for function Function_17
 * Generated by KISPE's test model C code scaffolder
 */

#include "function_17.h"
#include "../../../../../tf_common/tf_uart_comms.h"
#include <stdio.h>

// Constructor (unused)
void function_17_startup(void)
{
}

// Use the function number to determine a unique bit position for this function, wrapping around at 32
static const asn1SccT_UInt32 iMyFunctionNumber = 17; 
static const asn1SccT_UInt32 iMyBitPosition = 17 % 32; 

// Sporadic interface implementation. Receives a bitfield, sets its own bit, and passes it on to the next function in the chain
void function_17_PI_sp(const asn1SccT_UInt32 *IN_p1)
{
    // Set the bit at our bit position and pass on to next SP interface
    asn1SccT_UInt32 iNextValue = *IN_p1 | (1 << iMyBitPosition);
    function_17_RI_sp(&iNextValue);

    char aMsgBuff[100];
    sprintf(aMsgBuff, "Function %u (bit: %u): Received: %u. Sent: %u", iMyFunctionNumber, iMyBitPosition, *IN_p1, iNextValue);
    transmit_log_info(aMsgBuff);
}


