/* Body file for function Sender005
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "sender005.h"
//#include <stdio.h>


void sender005_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[Sender005] Startup");
}


void sender005_PI_PI_1_Send05( asn1SccT_Int32 *Framework_Result, asn1SccT_Boolean *Framework_Status )
{
asn1SccT_Int32 Parameter_N = 0;
asn1SccT_Boolean status = false;


    // TestStart000 shall invoke this function, which shall send
    // a message to Receiver001 as part of requirement MBEP-RT-FUN-220
    // and MBEP-RT-FUN-220, where 1:10 sender functions send to one
    // receiver function.

    Parameter_N = 500; // Expected by this interface Receiver001

    sender005_RI_PI_5( &Parameter_N, &status );

    // --
    // -- Return the result of Framework_Status from the Receiver001 function.
    // --

}

