/* Header file for function Function_8
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void function_8_startup(void);

/* Provided interfaces */
void function_8_PI_PI_8( const asn1SccT_Int32 * );


void function_8_PI_PI_cyclic_8( void );

/* Required interfaces */
extern void function_8_RI_PI_2( const asn1SccT_Int32 * );


#ifdef __cplusplus
}
#endif
