/* Body file for function test_death_report
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "test_death_report.h"
#include "../../../../../tf_common/tf_uart_comms.h"
#include "../../../../../tf_common/tf_test_results.h"
#include <stdio.h>
#include <Hal.h>
#include <DeathReport.h>

// Expected death report data points
static uint32_t DEATH_REPORT_EXPECTED_VALUE__EXCEPTION_ID       = 3;
static uint32_t DEATH_REPORT_EXPECTED_VALUE__REGISTER_R1        = 0x100159f0;
static uint32_t DEATH_REPORT_EXPECTED_VALUE__PROGRAM_COUNT      = 0x1000e3cc;
static uint32_t DEATH_REPORT_EXPECTED_VALUE__STACK_ADDRESS_1    = 0x100159f0;

#define MAX_DEATH_REPORT_STACK_TRACE_ENTRIES_TO_RENDER  5


// Flag to ensure we only report the test result at most once
static asn1SccT_Boolean bResetCheckDone = false;



// Link to the death report
extern const uint32_t DEATH_REPORT_BEGIN;   // Defined in the linker script linkcmds.intsram
static DeathReportWriter_DeathReport *const pDeathReport = (DeathReportWriter_DeathReport *const)&DEATH_REPORT_BEGIN;


// Resets the death report to zeroes
static void clear_death_report()
{
    // Reset the main header fields to zero
    pDeathReport->checksum = 0;
    pDeathReport->exception_id = 0;
    pDeathReport->registers.r1 = 0;
    pDeathReport->registers.r2 = 0;

    // Reset the stack trace control fields to zero
    pDeathReport->stack_trace_length = 0;
    pDeathReport->stack_trace_pointer = 0;

    // Reset all addresses in the stack trace to zero
    for(int i = 0; i < DEATH_REPORT_STACK_TRACE_SIZE; i++){
        pDeathReport->stack_trace[i] = 0;
    }

    transmit_log_info("Death report reset to zeroes");
}


// Renders whatever is in the death report
void transmit_the_death_report(void)
{
    char aMsgBuff[1000];

    transmit_bytes_over_uart("----------------\n");
    sprintf(aMsgBuff, "Death report:\n----------------\nchecksum: 0x%04x\nwas_seen: %d\npadding: %d\nexception_id: %lu\n", pDeathReport->checksum, pDeathReport->was_seen, pDeathReport->padding, (unsigned long)pDeathReport->exception_id);
    transmit_bytes_over_uart(aMsgBuff);
    sprintf(aMsgBuff, "r0: 0x%08x\nr1: 0x%08x\nr2: 0x%08x\nr3: 0x%08x\nr4: 0x%08x\nr5: 0x%08x\nr6: 0x%08x\nr7: 0x%08x\nr8: 0x%08x\nr9: 0x%08x\nr10: 0x%08x\nr11: 0x%08x\nr12: 0x%08x\nmsp: 0x%08x\npsp: 0x%08x\nlr: 0x%08x\npc: 0x%08x\npsr: %x\n", pDeathReport->registers.r0, pDeathReport->registers.r1, pDeathReport->registers.r2, pDeathReport->registers.r3, pDeathReport->registers.r4, pDeathReport->registers.r5, pDeathReport->registers.r6, pDeathReport->registers.r7, pDeathReport->registers.r8, pDeathReport->registers.r9, pDeathReport->registers.r10, pDeathReport->registers.r11, pDeathReport->registers.r12, pDeathReport->registers.msp, pDeathReport->registers.psp, pDeathReport->registers.lr, pDeathReport->registers.pc, pDeathReport->registers.psr);
    transmit_bytes_over_uart(aMsgBuff);
    sprintf(aMsgBuff, "pri_mask: 0x%08x\nfault_mask: 0x%08x\nbase_pri: 0x%08x\ncontrol: 0x%08x\ncfsr: 0x%08x\nhfsr: 0x%08x\nmmar: 0x%08x\nbfar: 0x%08x\n", pDeathReport->registers.pri_mask, pDeathReport->registers.fault_mask, pDeathReport->registers.base_pri, pDeathReport->registers.control, pDeathReport->system_control_block.cfsr, pDeathReport->system_control_block.hfsr, pDeathReport->system_control_block.mmar, pDeathReport->system_control_block.bfar);
    transmit_bytes_over_uart(aMsgBuff);
    transmit_bytes_over_uart("----------------\n");

    // Render the stack track only if there are entries
    if (pDeathReport->stack_trace_length == 0) {
        transmit_bytes_over_uart("Stack trace: (empty)\n");
        transmit_bytes_over_uart("----------------\n");
    } else {
        uint32_t iLastIndexToRender = pDeathReport->stack_trace_length <= MAX_DEATH_REPORT_STACK_TRACE_ENTRIES_TO_RENDER ? pDeathReport->stack_trace_length - 1 : MAX_DEATH_REPORT_STACK_TRACE_ENTRIES_TO_RENDER - 1;
        sprintf(aMsgBuff, "Stack trace (%lu entries; Showing first %lu):\n----------------\n", (unsigned long)pDeathReport->stack_trace_length, (unsigned long)(iLastIndexToRender + 1));
        transmit_bytes_over_uart(aMsgBuff);
        for (uint32_t i = 0; i <= iLastIndexToRender; i++) {
            sprintf(aMsgBuff, "%03lu: 0x%08x\n", (unsigned long)i, pDeathReport->stack_trace[i]);
            transmit_bytes_over_uart(aMsgBuff);
        }
        if (pDeathReport->stack_trace_length > MAX_DEATH_REPORT_STACK_TRACE_ENTRIES_TO_RENDER) {
            transmit_bytes_over_uart("...\n");
        }
        transmit_bytes_over_uart("----------------\n");
    }
}


// Constructor
void test_death_report_startup(void)
{
    // Register the test that this TASTE Function will submit a result for
    testresult_register_test(TF_TEST_ID__TestDeathReport);
}


// Cyclic IF handler: trigger_reset
// Determines if a death report is found in RAM. If not, transmits the reset signal, then forces the app to crash
void test_death_report_PI_trigger_reset(void)
{
    // Only do this once
    if (bResetCheckDone) {
        return;
    }

    // Check for the r1 register value that is associated with the death report that this model forces
    if (pDeathReport->registers.r1 == DEATH_REPORT_EXPECTED_VALUE__REGISTER_R1) {

        // Our death report was found in RAM, so we don't need to do anything
        transmit_log_info("Death report found in RAM, skipping reset");
        bResetCheckDone = true;
        return;
    }

    // On first call simply warn about what we will do and send the "end" signal. The subsequent call will then actually create the UsageFault
    // This allows time for the UART comms to complete
    // (Could instead use Hal_SleepNs(), but that seems eratic, sleeping many orders of magnitude longer than requested)
    static int iCallCount = 0;
    if (iCallCount++ == 0) {

        // Send the reset signal to the UART other-end
        transmit_log_info("No death report found in RAM (checksum was 0): Transmitting reset signal and forcing crash");
        transmit_reset_signal();

    } else {

        // Force a crash
        volatile int a = 1969;
        volatile int b = 0;
        volatile int c = a / b;  // triggers UsageFault
        (void)c;
    }
}


// Cyclic IF handler: trigger_check
// If we reach this point a death report was found in RAM
// Check the contents of the death report and passes the test if it matches expectations
void test_death_report_PI_trigger_check(void)
{
    char aMsgBuff[160];
    static asn1SccT_Boolean bResultReported = false;

    // Only do this once
    if (bResultReported) {
        return;
    }

    // Buffer the values locally (useful for gdb debugging)
    uint16_t iCheckSum          = pDeathReport->checksum;
    uint32_t iExceptionId       = pDeathReport->exception_id;
    uint32_t iRegisterR1        = pDeathReport->registers.r1;
    uint32_t iProgramCounter    = pDeathReport->registers.pc;
    uint32_t iStackAddress1     = pDeathReport->stack_trace[1];

    sprintf(aMsgBuff, "DeathReport: checksum: 0x%04x; exception_id: 0x%08x; r1: 0x%08x; pc: 0x%08x; stack_trace[1]: 0x%08x",
            iCheckSum, iExceptionId, iRegisterR1, iProgramCounter, iStackAddress1);
    transmit_log_info(aMsgBuff);
    sprintf(aMsgBuff, "Expecting  : checksum: (not zero); exception_id: 0x%08x; r1: 0x%08x; pc: 0x%08x; stack_trace[1]: 0x%08x",
            DEATH_REPORT_EXPECTED_VALUE__EXCEPTION_ID, DEATH_REPORT_EXPECTED_VALUE__REGISTER_R1, DEATH_REPORT_EXPECTED_VALUE__PROGRAM_COUNT, DEATH_REPORT_EXPECTED_VALUE__STACK_ADDRESS_1);
    transmit_log_info(aMsgBuff);

    // Evaluate pass/fail
    if (   iCheckSum == 0
        || iExceptionId != DEATH_REPORT_EXPECTED_VALUE__EXCEPTION_ID
        || iRegisterR1 != DEATH_REPORT_EXPECTED_VALUE__REGISTER_R1
        || iProgramCounter != DEATH_REPORT_EXPECTED_VALUE__PROGRAM_COUNT
        || iStackAddress1 != DEATH_REPORT_EXPECTED_VALUE__STACK_ADDRESS_1
        )
    {
        testresult_report_fail(TF_TEST_ID__TestDeathReport, "Death report found but not as expected");
        transmit_the_death_report();
    } else {
        testresult_report_pass(TF_TEST_ID__TestDeathReport);
    }

    // Reset the death report
    clear_death_report();

    // Set the flag to avoid doing this again
    bResultReported = true;
}




