/* Body file for function test_death_report
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "test_death_report.h"
#include "../../../../../tf_common/tf_uart_comms.h"
#include "../../../../../tf_common/tf_test_results.h"
#include <stdio.h>
#include <Hal.h>
#include <DeathReport.h>


#define MAX_DEATH_REPORT_STACK_TRACE_ENTRIES_TO_RENDER 5
#define ENABLE_RESET 0

// Flag to ensure we only report the test result at most once
static asn1SccT_Boolean bResetCheckDone = false;



// Link to the death report
extern const uint32_t DEATH_REPORT_BEGIN;   // Defined in the linker script linkcmds.intsram
static DeathReportWriter_DeathReport *const pDeathReport = (DeathReportWriter_DeathReport *const)&DEATH_REPORT_BEGIN;


// Resets the death report to zeroes
static void clean_death_report()
{
    // Reset the main header fields to zero
    pDeathReport->checksum = 0;
    pDeathReport->exception_id = 0;
    pDeathReport->registers.r1 = 0;
    pDeathReport->registers.r2 = 0;

    // Reset the stack trace control fields to zero
    pDeathReport->stack_trace_length = 0;
    pDeathReport->stack_trace_pointer = 0;

    // Reset all addresses in the stack trace to zero
    for(int i = 0; i < DEATH_REPORT_STACK_TRACE_SIZE; i++){
        pDeathReport->stack_trace[i] = 0;
    }

    transmit_log_info("Death report reset to zeroes");
}


// Renders whatever is in the death report
void transmit_the_death_report(void)
{
    char aMsgBuff[1000];

    transmit_bytes_over_uart("----------------\n");
    sprintf(aMsgBuff, "Death report:\n----------------\nchecksum: 0x%04x\nwas_seen: %d\npadding: %d\nexception_id: %lu\n", pDeathReport->checksum, pDeathReport->was_seen, pDeathReport->padding, pDeathReport->exception_id);
    transmit_bytes_over_uart(aMsgBuff);
    sprintf(aMsgBuff, "r0: 0x%08x\nr1: 0x%08x\nr2: 0x%08x\nr3: 0x%08x\nr4: 0x%08x\nr5: 0x%08x\nr6: 0x%08x\nr7: 0x%08x\nr8: 0x%08x\nr9: 0x%08x\nr10: 0x%08x\nr11: 0x%08x\nr12: 0x%08x\nmsp: 0x%08x\npsp: 0x%08x\nlr: 0x%08x\npc: 0x%08x\npsr: %x\n", pDeathReport->registers.r0, pDeathReport->registers.r1, pDeathReport->registers.r2, pDeathReport->registers.r3, pDeathReport->registers.r4, pDeathReport->registers.r5, pDeathReport->registers.r6, pDeathReport->registers.r7, pDeathReport->registers.r8, pDeathReport->registers.r9, pDeathReport->registers.r10, pDeathReport->registers.r11, pDeathReport->registers.r12, pDeathReport->registers.msp, pDeathReport->registers.psp, pDeathReport->registers.lr, pDeathReport->registers.pc, pDeathReport->registers.psr);
    transmit_bytes_over_uart(aMsgBuff);
    sprintf(aMsgBuff, "pri_mask: 0x%08x\nfault_mask: 0x%08x\nbase_pri: 0x%08x\ncontrol: 0x%08x\ncfsr: 0x%08x\nhfsr: 0x%08x\nmmar: 0x%08x\nbfar: 0x%08x\n", pDeathReport->registers.pri_mask, pDeathReport->registers.fault_mask, pDeathReport->registers.base_pri, pDeathReport->registers.control, pDeathReport->system_control_block.cfsr, pDeathReport->system_control_block.hfsr, pDeathReport->system_control_block.mmar, pDeathReport->system_control_block.bfar);
    transmit_bytes_over_uart(aMsgBuff);
    transmit_bytes_over_uart("----------------\n");

    // Render the stack track only if there are entries
    if (pDeathReport->stack_trace_length == 0) {
        transmit_bytes_over_uart("Stack trace: (empty)\n");
        transmit_bytes_over_uart("----------------\n");
    } else {
        uint32_t iLastIndexToRender = pDeathReport->stack_trace_length <= MAX_DEATH_REPORT_STACK_TRACE_ENTRIES_TO_RENDER ? pDeathReport->stack_trace_length - 1 : MAX_DEATH_REPORT_STACK_TRACE_ENTRIES_TO_RENDER - 1;
        sprintf(aMsgBuff, "Stack trace (%lu entries; Showing first %lu):\n----------------\n", pDeathReport->stack_trace_length, iLastIndexToRender + 1);
        transmit_bytes_over_uart(aMsgBuff);
        for (uint32_t i = 0; i <= iLastIndexToRender; i++) {
            sprintf(aMsgBuff, "%03lu: 0x%08x\n", i, pDeathReport->stack_trace[i]);
            transmit_bytes_over_uart(aMsgBuff);
        }
        if (pDeathReport->stack_trace_length > MAX_DEATH_REPORT_STACK_TRACE_ENTRIES_TO_RENDER) {
            transmit_bytes_over_uart("...\n");
        }
        transmit_bytes_over_uart("----------------\n");
    }
}


// Constructor
void test_death_report_startup(void)
{
    // Register the test that this TASTE Function will submit a result for
    testresult_register_test(TF_TEST_ID__TestDeathReport);
}


// Cyclic IF handler: trigger_reset
// Determines if a death report is found in RAM. If not, transmits the reset signal, then forces the app to crash
void test_death_report_PI_trigger_reset(void)
{
    // Only do this once
    if (bResetCheckDone) {
        return;
    }

    // Check for a non-zero checksum
    if (pDeathReport->checksum != 0) {

        // A death report was found in RAM, so we don't need to do anything
        transmit_log_info("Death report found in RAM, skipping reset");
        bResetCheckDone = true;
        return;
    }

    // On first call simply warn about what we will do ans send the "end" signal. The subsequent call will then actually do the UsageFault
    // This allows time for the UART comms to complete
    // (Could instead use Hal_SleepNs(), but that seems eratic, sleeping many orders or magnitude longer than requested)
    static int iCallCount = 0;
    if (iCallCount++ == 0) {
        transmit_log_info("No death report found in RAM (checksum was 0): Transmitting reset signal and forcing crash");
        transmit_reset_signal();

    } else {

        // Force a crash
        volatile int a = 1969;
        volatile int b = 0;
        volatile int c = a / b;  // triggers UsageFault
        (void)c;
    }
}


// Cyclic IF handler: trigger_check
// If we reach this point a death report was found in RAM
// Check the contents of the death report and passes the test if it matches expectations
void test_death_report_PI_trigger_check(void)
{
    char aMsgBuff[100];
    static asn1SccT_Boolean bResultReported = false;

    // Only do this once
    if (bResultReported) {
        return;
    }

    // Fetch and report the death report
//    transmit_the_death_report();

    // TODO: Check its contents against expectations and report the result

    // Reset the death report
//    clean_death_report();
    // Update the checksum
    sprintf(aMsgBuff, "pDeathReport->checksum is: %u", pDeathReport->checksum);
    transmit_log_info(aMsgBuff);
    pDeathReport->checksum = 0;
    sprintf(aMsgBuff, "   --> pDeathReport->checksum updated to: %u", pDeathReport->checksum);
    transmit_log_info(aMsgBuff);

    transmit_end_signal();

    // Set the flag to avoid doing this again
    bResultReported = true;
}




