/* Body file for function MQueueCallBack12
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "mqueuecallback12.h"
//#include <stdio.h>


void mqueuecallback12_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[MQueueCallBack12] Startup");
}

void mqueuecallback12_PI_PI_1( void )
{
    // to be implemented
}


