/* Body file for function Sender008
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "sender008_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void sender008_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void CInitsender008(void);

extern void init_receiver001(void);
extern unsigned receiver001_initialized;
unsigned sender008_initialized = 0;
void init_sender008(void)
{
   if (0 == sender008_initialized) {
      sender008_initialized = 1;
      // Call user code startup function
      extern void sender008_startup(void);
      sender008_startup();
      // Iterate over all synchronous RIs, and call their parent's
      // init function. Multiple calls are prevented by the "init" guard.
      if (0 == receiver001_initialized) {
          init_receiver001();
      }
      sender008_initialized = 2;
   }
}
void sender008_PI_1(void)
{

   //  Directly call user code, no parameters to pass
   extern void sender008_PI_PI_1(void);
   sender008_PI_PI_1();
   // puts ("sender008_pi_1 called");
}

