/* Body file for function TestUnProtOUT05
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "testunprotout05_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void testunprotout05_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void CInittestunprotout05(void);

unsigned testunprotout05_initialized = 0;
void init_testunprotout05(void)
{
   if (0 == testunprotout05_initialized) {
      testunprotout05_initialized = 1;
      // Call user code startup function
      extern void testunprotout05_startup(void);
      testunprotout05_startup();
      testunprotout05_initialized = 2;
   }
}
void testunprotout05_PI_1
      (char *OUT_p1, size_t *OUT_p1_len,
       char *OUT_p2, size_t *OUT_p2_len,
       char *OUT_p3, size_t *OUT_p3_len,
       char *OUT_p4, size_t *OUT_p4_len,
       char *OUT_p5, size_t *OUT_p5_len,
       char *OUT_p6, size_t *OUT_p6_len)

{
   sender_pid = testunprotout05_pi_1_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void testunprotout05_PI_PI_1
      (asn1SccT_Int32 *,
       asn1SccT_UInt32 *,
       asn1SccT_Int8 *,
       asn1SccT_UInt8 *,
       asn1SccT_Boolean *,
       asn1SccT_Boolean *);





   // Call user code
   testunprotout05_PI_PI_1 ((asn1SccT_Int32 *)OUT_p1, (asn1SccT_UInt32 *)OUT_p2, (asn1SccT_Int8 *)OUT_p3, (asn1SccT_UInt8 *)OUT_p4, (asn1SccT_Boolean *)OUT_p5, (asn1SccT_Boolean *)OUT_p6);

}

