/* Body file for function RcvACN04
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "rcvacn04.h"
//#include <stdio.h>


void rcvacn04_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[RcvACN04] Startup");
}

void rcvacn04_PI_PI_1_ACN04
      (const asn1SccPID *IN_p1,
       asn1SccPID *OUT_p2)

{
    asn1SccPID encoded_input;


    // ---------------------------------------------------------
    // -- This test shall take the incoming asn1SccPID, which --
    // -- has been ACN encoded, this is returned as is        --
    // -- for the SendACN() to test that it has been encoded  --
    // -- and encoded correctly.                              --
    // ---------------------------------------------------------

    encoded_input = *IN_p1;
    *OUT_p2 = encoded_input;

}


