/* Body file for function Receiver013
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "receiver013_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void receiver013_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void CInitreceiver013(void);

unsigned receiver013_initialized = 0;
void init_receiver013(void)
{
   if (0 == receiver013_initialized) {
      receiver013_initialized = 1;
      // Call user code startup function
      extern void receiver013_startup(void);
      receiver013_startup();
      receiver013_initialized = 2;
   }
}
void receiver013_PI_1_SR13
      (char *OUT_p1, size_t *OUT_p1_len)

{
   sender_pid = receiver013_pi_1_sr13_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void receiver013_PI_PI_1_SR13
      (asn1SccT_Int32 *);





   // Call user code
   receiver013_PI_PI_1_SR13 ((asn1SccT_Int32 *)OUT_p1);

}

