/* Header file for function Function_7
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void function_7_startup(void);

/* Provided interfaces */
void function_7_PI_PI_7( const asn1SccT_Int32 * );


void function_7_PI_PI_cyclic_7( void );

/* Required interfaces */
extern void function_7_RI_PI_8( const asn1SccT_Int32 * );


#ifdef __cplusplus
}
#endif
