/* Header file for function Paketizer002C
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void paketizer002c_startup(void);

/* Provided interfaces */
void paketizer002c_PI_PI_1( asn1SccT_Int32 *, asn1SccT_Boolean * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
