/* Body file for function test_death_report
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "test_death_report_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void test_death_report_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void adainit(void);

unsigned test_death_report_initialized = 0;
void init_test_death_report(void)
{
   if (0 == test_death_report_initialized) {
      test_death_report_initialized = 1;
      // Call user code startup function
      extern void test_death_report_startup(void);
      test_death_report_startup();
      test_death_report_initialized = 2;
   }
}
void test_death_report_trigger_check(void)
{

   //  Directly call user code, no parameters to pass
   extern void test_death_report_PI_trigger_check(void);
   test_death_report_PI_trigger_check();
   // puts ("test_death_report_trigger_check called");
}




void test_death_report_trigger_reset(void)
{

   //  Directly call user code, no parameters to pass
   extern void test_death_report_PI_trigger_reset(void);
   test_death_report_PI_trigger_reset();
   // puts ("test_death_report_trigger_reset called");
}

