/* Header file for function Prot05IFIN
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm_if-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

/* The purpose of this file is to provide a wrapper around the user code,
 * with a single interface that is independent of the implementation language
 * of the function. The parameters of each PI are blackboxes encoded
 * in the form specified in the interface view (Native, uPER, or ACN)
*/

#pragma once
#if defined(__unix__) || defined (__MSP430__)
   #include <stdlib.h>
   #include <stdio.h>
#else
   typedef unsigned size_t;
#endif

#include "C_ASN1_Types.h"
#ifdef __cplusplus
extern "C" {
#endif

#include "prot05ifin.h"

// Function initialization - calls user startup code of all dependent functions
void init_prot05ifin(void);


/* Provided interfaces */
void prot05ifin_PI_1_5IN
      (const char *IN_p1, size_t IN_p1_len,
       const char *IN_p2, size_t IN_p2_len,
       const char *IN_p3, size_t IN_p3_len,
       const char *IN_p4, size_t IN_p4_len,
       const char *IN_p5, size_t IN_p5_len,
       char *OUT_p6, size_t *OUT_p6_len);


#ifdef __cplusplus
}
#endif

