/* File generated by kazoo for TASTE - do not edit */
#ifndef INTERFACE_INFO_H
#define INTERFACE_INFO_H
#include <limits.h>
#include <rtems.h>

#define RUNTIME_THREAD_COUNT ( 1 + 123 )
#define RUNTIME_CYCLIC_INTERFACE_COUNT ( 0 + 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1+ 1 )
#define MAX_THREAD_NAME_SIZE 64
#define NANOSECONDS_IN_MILLISECOND 1000000ULL

enum interfaces_enum{
    
    function_10_pi_1_cyclic,

    function_10_pi_2,

    function_11_pi_1_cyclic,

    function_11_pi_2,

    function_12_pi_1_cyclic,

    function_12_pi_2,

    function_13_pi_1_cyclic,

    function_13_pi_2,

    function_14_pi_1_cyclic,

    function_14_pi_2,

    function_15_pi_1_cyclic,

    function_15_pi_2,

    function_16_pi_1_cyclic,

    function_16_pi_2,

    function_17_pi_1_cyclic,

    function_17_pi_2,

    function_18_pi_1_cyclic,

    function_18_pi_2,

    function_19_pi_1_cyclic,

    function_19_pi_2,

    function_1_pi_cyclic_1,

    function_1_pi_start001,

    function_20_pi_1_cyclic,

    function_20_pi_2_20,

    function_21_pi_1_cyclic,

    function_21_pi_2,

    function_22_pi_1_cyclic,

    function_22_pi_2,

    function_23_pi_2,

    function_23_pi_cyclic,

    function_24_pi_1_cyclic,

    function_24_pi_2,

    function_25_pi_1_cyclic,

    function_26_pi_1_cyclic,

    function_26_pi_2_26,

    function_27_pi_1_cyclic,

    function_27_pi_27,

    function_28_pi_1_cyclic,

    function_28_pi_2,

    function_29_pi_1_cyclic,

    function_29_pi_2,

    function_2_pi_2,

    function_2_pi_cyclic_2,

    function_30_pi_1_cyclic,

    function_30_pi_2,

    function_31_pi_1_cyclic,

    function_31_pi_2,

    function_32_pi_1_cyclic,

    function_32_pi_2,

    function_33_pi_1_cyclic,

    function_33_pi_2,

    function_34_pi_1_clyclic,

    function_34_pi_2,

    function_35_pi_1_cyclic,

    function_35_pi_2,

    function_36_pi_1_cyclic,

    function_36_pi_2,

    function_37_pi_1_cyclic,

    function_37_pi_2,

    function_38_pi_1_cyclic,

    function_38_pi_2,

    function_39_pi_1_cyclic,

    function_39_pi_2,

    function_3_pi_3,

    function_3_pi_cyclic_3,

    function_40_pi_1_cyclic,

    function_40_pi_2,

    function_41_pi_1_cyclic,

    function_41_pi_2,

    function_42_pi_1_cyclic,

    function_42_pi_2,

    function_43_pi_1_cyclic,

    function_43_pi_2,

    function_44_pi_1_cyclic,

    function_44_pi_2,

    function_45_pi_1_cyclic,

    function_45_pi_2,

    function_46_pi_1_cyclic,

    function_46_pi_2,

    function_47_pi_1_cyclic,

    function_47_pi_2,

    function_48_pi_1_cyclic,

    function_48_pi_2,

    function_4_pi_4,

    function_4_pi_cyclic_4,

    function_5_pi_5,

    function_5_pi_cyclic_5,

    function_6_pi_6,

    function_6_pi_cyclic_6,

    function_7_pi_7,

    function_7_pi_cyclic_7,

    function_8_pi_8,

    function_8_pi_cyclic_8,

    function_9_pi_1_cyclic,

    function_9_pi_2,

    mqueuecallback12_pi_1,

    partition_1_timer_manager_tick,

    receiver001_pi_1,

    receiver001_pi_10,

    receiver001_pi_2,

    receiver001_pi_3,

    receiver001_pi_4,

    receiver001_pi_5,

    receiver001_pi_6,

    receiver001_pi_7,

    receiver001_pi_8,

    receiver001_pi_9,

    sender001_pi_1_cyclic,

    sender001_pi_2,

    sender002_pi_1,

    sender003_pi_1,

    sender004_pi_1,

    sender006_pi_1,

    sender007_pi_1,

    sender008_pi_1,

    sender009_pi_1,

    sender010_pi_1,

    sender011_pi_1,

    sernder005_pi_1,

    testcyclic05_pi_1,

    testsdl08_mytime,

    testsdl08_pi_startsdl08,

    teststart00_pi_1_cyclic,

};

typedef struct {
    rtems_id id;
    char name[MAX_THREAD_NAME_SIZE];
    uint64_t thread_execution_time;
    uint64_t min_thread_execution_time;
    uint64_t max_thread_execution_time;
    double mean_thread_execution_time;
    uint64_t execution_time_counter;
} thread_info;

extern thread_info threads_info[RUNTIME_THREAD_COUNT];

extern rtems_id interface_to_queue_map[RUNTIME_THREAD_COUNT];

extern uint32_t maximum_queued_items[RUNTIME_THREAD_COUNT];
#endif
