/* Body file for function EscaperTest002B
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "escapertest002b_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void escapertest002b_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void CInitescapertest002b(void);

unsigned escapertest002b_initialized = 0;
void init_escapertest002b(void)
{
   if (0 == escapertest002b_initialized) {
      escapertest002b_initialized = 1;
      // Call user code startup function
      extern void escapertest002b_startup(void);
      escapertest002b_startup();
      escapertest002b_initialized = 2;
   }
}
void escapertest002b_PI_1
      (char *OUT_p1, size_t *OUT_p1_len,
       char *OUT_p2, size_t *OUT_p2_len)

{
   sender_pid = escapertest002b_pi_1_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void escapertest002b_PI_PI_1
      (asn1SccT_Int32 *,
       asn1SccT_Boolean *);





   // Call user code
   escapertest002b_PI_PI_1 ((asn1SccT_Int32 *)OUT_p1, (asn1SccT_Boolean *)OUT_p2);

}

