/* Body file for function Test_Function
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "test_function.h"
#include "../../../../../tf_common/tf_uart_comms.h"
#include <Hal.h>
#include <stdio.h>


void test_function_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[Test_Function] Startup");
}

void test_function_PI_node31result(const asn1SccT_UInt32 *IN_p1)
{
    char aMsgBuff[100];
    sprintf(aMsgBuff, "Test Function got from Function 31: %lu. Uptime seconds: %llu", *IN_p1, Hal_GetElapsedTimeInNs() / 1000000000);
    transmit_log_info(aMsgBuff);

    // Start next section of chain again from 1
    asn1SccT_UInt32 iNextValue = 1;
    test_function_RI_sp(&iNextValue);
}


void test_function_PI_node40result(const asn1SccT_UInt32 *IN_p1)
{
    char aMsgBuff[100];
    sprintf(aMsgBuff, "Test Function reached. Function 32: %lu. Uptime seconds: %llu", *IN_p1, Hal_GetElapsedTimeInNs() / 1000000000);
    transmit_log_info(aMsgBuff);
}

