/* Body file for function Test_Function
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "test_function.h"
#include "../../../../../tf_common/tf_uart_comms.h"
#include "../../../../../tf_common/tf_test_results.h"
#include <Hal.h>
#include <stdio.h>

// Values we expect to receive on each of the two sporadic interfaces from the 40 SP-interface chain functions
static const asn1SccT_UInt32 EXPECTED_VALUE__FUNCTION_31 = 4294967295;
static const asn1SccT_UInt32 EXPECTED_VALUE__FUNCTION_40 = 511;
static const asn1SccT_UInt32 EXPECTED_MINIM_COUNT_OF_TRIGGER2_CALLS = 4;

// Buffers to hold values we actually received
static asn1SccT_UInt32 iReceivedFromFunction31      = 0;
static asn1SccT_UInt32 iReceivedFromFunction40      = 0;
static asn1SccT_Boolean bReceivedOnProtectedIF      = false;
static asn1SccT_Boolean bReceivedOnUnprotectedIF    = false;
static asn1SccT_Boolean bReceivedZeroParamSPIF      = false;
static asn1SccT_UInt32 iNumTrigger2Calls            = 0;


// Constructor
void test_function_startup(void)
{
    // Register the test
    testresult_register_test(TF_TEST_ID__TestMaxTasks);
}


// Handler for the protected interface
void test_function_PI_protected1( void )
{
    // Log what we received
    transmit_log_info("Test Function received request on Protected interface");

    // Register this hit
    bReceivedOnProtectedIF = true;
}


// Handler for the unprotected interface
void test_function_PI_unprotected1( void )
{
    // Log what we received
    transmit_log_info("Test Function received request on Unprotected interface");

    // Register this hit
    bReceivedOnUnprotectedIF = true;
}


// Handler for the zero-parameter Sporadic interface
void test_function_PI_spzero( void )
{
    // Log what we received
    transmit_log_info("Test Function received request on zero-parameter Sporadic interface");

    // Register this hit
    bReceivedZeroParamSPIF = true;
}


// Handler for trigger2 - a random cyclic interface to bring the IF count up to 48
void test_function_PI_trigger2(void)
{
    // Log this invocation
    char aMsgBuff[100];
    sprintf(aMsgBuff, "Test Function got from Cycling interface trigger2. Uptime seconds: %llu", Hal_GetElapsedTimeInNs() / 1000000000);
    transmit_log_info(aMsgBuff);

    // Update the call count
    iNumTrigger2Calls++;
}


// Handler for the SP-interface from Function 31
void test_function_PI_node31result(const asn1SccT_UInt32 *IN_p1)
{
    // Log what we received
    char aMsgBuff[100];
    sprintf(aMsgBuff, "Test Function got from Function 31: %u", *IN_p1);
    transmit_log_info(aMsgBuff);

    // Store this value
    iReceivedFromFunction31 = *IN_p1;

    // Start next section of chain again from 1
    asn1SccT_UInt32 iNextValue = 1;
    test_function_RI_sp(&iNextValue);
}


// Handler for the SP-interface from Function 40
void test_function_PI_node40result(const asn1SccT_UInt32 *IN_p1)
{
    // Log what we received
    char aMsgBuff[100];
    sprintf(aMsgBuff, "Test Function got from Function 40: %u", *IN_p1);
    transmit_log_info(aMsgBuff);

    // Store this value
    iReceivedFromFunction40 = *IN_p1;
}


// Called periodically by cyclic interface. We collate test inputs and decide pass/fail
void test_function_PI_trigger( void )
{
    char aMsgBuff[100];

    // Failed to get expected value on the Function 31 Sporadic interface?
    if (iReceivedFromFunction31 != EXPECTED_VALUE__FUNCTION_31)
    {
        sprintf(aMsgBuff, "Expected %u from Function 31 but got %u", EXPECTED_VALUE__FUNCTION_31, iReceivedFromFunction31);
        testresult_report_fail(TF_TEST_ID__TestMaxTasks, aMsgBuff);
    }

    // Failed to get expected value on the Function 40 Sporadic interface?
    else if (iReceivedFromFunction40 != EXPECTED_VALUE__FUNCTION_40)
    {
        sprintf(aMsgBuff, "Expected %u from Function 40 but got %u", EXPECTED_VALUE__FUNCTION_40, iReceivedFromFunction40);
        testresult_report_fail(TF_TEST_ID__TestMaxTasks, aMsgBuff);
    }

    // Failed to get a request on the protected interface?
    else if (!bReceivedOnProtectedIF)
    {
        testresult_report_fail(TF_TEST_ID__TestMaxTasks, "Expected a request on the Protected interface but got none");
    }

    // Failed to get a request on the protected interface?
    else if (!bReceivedOnUnprotectedIF)
    {
        testresult_report_fail(TF_TEST_ID__TestMaxTasks, "Expected a request on the Unprotected interface but got none");
    }

    // Failed to get a request on the protected interface?
    else if (!bReceivedZeroParamSPIF)
    {
        testresult_report_fail(TF_TEST_ID__TestMaxTasks, "Expected a request on the zero-paramater Sporadic interface but got none");
    }

    // Failed to get the expected count of calls on trigger2 IF?
    else if (iNumTrigger2Calls < EXPECTED_MINIM_COUNT_OF_TRIGGER2_CALLS)
    {
        sprintf(aMsgBuff, "Expected at least %u calls on the trigger2 Cyclic interface but only got %u", EXPECTED_MINIM_COUNT_OF_TRIGGER2_CALLS, iNumTrigger2Calls);
        testresult_report_fail(TF_TEST_ID__TestMaxTasks, aMsgBuff);
    }

    // Else it must be a pass
    else
    {
        testresult_report_pass(TF_TEST_ID__TestMaxTasks);
    }
}




