/* Header file for function RcvACN03
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void rcvacn03_startup(void);

/* Provided interfaces */
void rcvacn03_PI_PI_1_ACN03( const asn1SccT_Boolean *, asn1SccT_Boolean * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
