/* Header file for function StartSendTest
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdio.h>

void startsendtest_startup(void);

/* Provided interfaces */
void startsendtest_PI_PI_2_Start_Test( asn1SccT_Int32 *, asn1SccT_Boolean * );

/* Required interfaces */
extern void startsendtest_RI_PI_1_Start_Sender_11( asn1SccT_Int32 *, asn1SccT_Boolean * );


#ifdef __cplusplus
}
#endif
