/* Body file for function StartSendTest
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "startsendtest.h"
#include "../../../../test_defines.h"           // Custom include, NOT managed by TASTE
#include <stdio.h>


void startsendtest_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[StartSendTest] Startup");
}

void startsendtest_PI_PI_1_Start_Sent_Test
      (asn1SccT_Int32 *OUT_p1,
       asn1SccT_Boolean *OUT_p2)

{
   // Write your code here


   extern void startsendtest_RI_PI_1_Start_Sender_11( &OUT_p1, &OUT_p2 )

}





