/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>

#include "asn1crt_encoding.h"
#include "asn1crt_encoding_uper.h"
#include "asn1crt_encoding_acn.h"

#include "dataview-uniq.h"


flag asn1SccMyInteger_Equal(const asn1SccMyInteger* pVal1, const asn1SccMyInteger* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccMyInteger_IsConstraintValid(const asn1SccMyInteger* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 10000UL);
    *pErrCode = ret ? 0 :  ERR_MYINTEGER;

	return ret;
}

#ifdef __cplusplus
const asn1SccMyInteger asn1SccMyInteger_constant = 0UL;
#endif

void asn1SccMyInteger_Initialize(asn1SccMyInteger* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccMyInteger)asn1SccMyInteger_constant;
}

flag asn1SccMyInteger_Encode(const asn1SccMyInteger* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccMyInteger_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 10000);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccMyInteger_Decode(asn1SccMyInteger* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 10000);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_MYINTEGER;

	return ret  && asn1SccMyInteger_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccMyInteger_ACN_Encode(const asn1SccMyInteger* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccMyInteger_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 10000);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccMyInteger_ACN_Decode(asn1SccMyInteger* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 10000);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_MYINTEGER;

    return ret && asn1SccMyInteger_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccCounter_Equal(const asn1SccCounter* pVal1, const asn1SccCounter* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccCounter_IsConstraintValid(const asn1SccCounter* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 1000UL);
    *pErrCode = ret ? 0 :  ERR_COUNTER;

	return ret;
}

#ifdef __cplusplus
const asn1SccCounter asn1SccCounter_constant = 0UL;
#endif

void asn1SccCounter_Initialize(asn1SccCounter* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccCounter)asn1SccCounter_constant;
}

flag asn1SccCounter_Encode(const asn1SccCounter* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccCounter_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 1000);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccCounter_Decode(asn1SccCounter* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 1000);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_COUNTER;

	return ret  && asn1SccCounter_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccCounter_ACN_Encode(const asn1SccCounter* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccCounter_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 1000);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccCounter_ACN_Decode(asn1SccCounter* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 1000);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_COUNTER;

    return ret && asn1SccCounter_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccT_Int32_Equal(const asn1SccT_Int32* pVal1, const asn1SccT_Int32* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccT_Int32_IsConstraintValid(const asn1SccT_Int32* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((-2147483648LL <= (*(pVal))) && ((*(pVal)) <= 2147483647LL));
    *pErrCode = ret ? 0 :  ERR_T_INT32;

	return ret;
}

#ifdef __cplusplus
const asn1SccT_Int32 asn1SccT_Int32_constant = 0LL;
#endif

void asn1SccT_Int32_Initialize(asn1SccT_Int32* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccT_Int32)asn1SccT_Int32_constant;
}

flag asn1SccT_Int32_Encode(const asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Int32_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, (*(pVal)), -2147483648LL, 2147483647LL);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_Int32_Decode(asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, pVal, -2147483648LL, 2147483647LL);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_T_INT32;

	return ret  && asn1SccT_Int32_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccT_Int32_ACN_Encode(const asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Int32_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, (*(pVal)), -2147483648LL, 2147483647LL);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_Int32_ACN_Decode(asn1SccT_Int32* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, pVal, -2147483648LL, 2147483647LL);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_T_INT32;

    return ret && asn1SccT_Int32_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccT_UInt32_Equal(const asn1SccT_UInt32* pVal1, const asn1SccT_UInt32* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccT_UInt32_IsConstraintValid(const asn1SccT_UInt32* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 4294967295UL);
    *pErrCode = ret ? 0 :  ERR_T_UINT32;

	return ret;
}

#ifdef __cplusplus
const asn1SccT_UInt32 asn1SccT_UInt32_constant = 0UL;
#endif

void asn1SccT_UInt32_Initialize(asn1SccT_UInt32* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccT_UInt32)asn1SccT_UInt32_constant;
}

flag asn1SccT_UInt32_Encode(const asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_UInt32_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 4294967295LL);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_UInt32_Decode(asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967295LL);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_T_UINT32;

	return ret  && asn1SccT_UInt32_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccT_UInt32_ACN_Encode(const asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_UInt32_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 4294967295LL);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_UInt32_ACN_Decode(asn1SccT_UInt32* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 4294967295LL);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_T_UINT32;

    return ret && asn1SccT_UInt32_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccT_Runtime_Error_Equal(const asn1SccT_Runtime_Error* pVal1, const asn1SccT_Runtime_Error* pVal2)
{
	flag ret=TRUE;

    ret = (pVal1->kind == pVal2->kind);
    if (ret) {
    	switch(pVal1->kind)
    	{
    	case T_Runtime_Error_noerror_PRESENT:
    		ret = (pVal1->u.noerror == pVal2->u.noerror);
    		break;
    	case T_Runtime_Error_encodeerror_PRESENT:
    		ret = (pVal1->u.encodeerror == pVal2->u.encodeerror);
    		break;
    	case T_Runtime_Error_decodeerror_PRESENT:
    		ret = (pVal1->u.decodeerror == pVal2->u.decodeerror);
    		break;
    	default: /*COVERAGE_IGNORE*/
    		ret = FALSE;    /*COVERAGE_IGNORE*/
    	}
    } /*COVERAGE_IGNORE*/
	return ret;

}

flag asn1SccT_Runtime_Error_IsConstraintValid(const asn1SccT_Runtime_Error* pVal, int* pErrCode)
{
    flag ret = TRUE;
    switch (pVal->kind) {
        case T_Runtime_Error_noerror_PRESENT : 
            ret = asn1SccT_UInt32_IsConstraintValid((&(pVal->u.noerror)), pErrCode);
            break;          
        case T_Runtime_Error_encodeerror_PRESENT : 
            ret = asn1SccT_Int32_IsConstraintValid((&(pVal->u.encodeerror)), pErrCode);
            break;          
        case T_Runtime_Error_decodeerror_PRESENT : 
            ret = asn1SccT_Int32_IsConstraintValid((&(pVal->u.decodeerror)), pErrCode);
            break;          
        default: /*COVERAGE_IGNORE*/
    	    *pErrCode = ERR_T_RUNTIME_ERROR;      /*COVERAGE_IGNORE*/
    	    ret = FALSE;                               /*COVERAGE_IGNORE*/
    }

	return ret;
}

#ifdef __cplusplus
const asn1SccT_Runtime_Error asn1SccT_Runtime_Error_constant = {.kind = T_Runtime_Error_noerror_PRESENT, .u.noerror = 0UL};
#endif

void asn1SccT_Runtime_Error_Initialize(asn1SccT_Runtime_Error* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccT_Runtime_Error)asn1SccT_Runtime_Error_constant;
}

flag asn1SccT_Runtime_Error_Encode(const asn1SccT_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Runtime_Error_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    switch(pVal->kind)
	    {
	    case T_Runtime_Error_noerror_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 2);
	    	ret = asn1SccT_UInt32_Encode((&(pVal->u.noerror)), pBitStrm, pErrCode, FALSE);
	    	break;
	    case T_Runtime_Error_encodeerror_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 2);
	    	ret = asn1SccT_Int32_Encode((&(pVal->u.encodeerror)), pBitStrm, pErrCode, FALSE);
	    	break;
	    case T_Runtime_Error_decodeerror_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 2, 0, 2);
	    	ret = asn1SccT_Int32_Encode((&(pVal->u.decodeerror)), pBitStrm, pErrCode, FALSE);
	    	break;
	    default:                            /*COVERAGE_IGNORE*/
	        *pErrCode = ERR_UPER_ENCODE_T_RUNTIME_ERROR;         /*COVERAGE_IGNORE*/
	        ret = FALSE;                    /*COVERAGE_IGNORE*/
	    }
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_Runtime_Error_Decode(asn1SccT_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	asn1SccSint asn1SccT_Runtime_Error_index_tmp;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &asn1SccT_Runtime_Error_index_tmp, 0, 2);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_T_RUNTIME_ERROR;
	if (ret) {
	    switch(asn1SccT_Runtime_Error_index_tmp)
	    {
	    case 0:
	    	pVal->kind = T_Runtime_Error_noerror_PRESENT;
	    	ret = asn1SccT_UInt32_Decode((&(pVal->u.noerror)), pBitStrm, pErrCode);
	    	break;
	    case 1:
	    	pVal->kind = T_Runtime_Error_encodeerror_PRESENT;
	    	ret = asn1SccT_Int32_Decode((&(pVal->u.encodeerror)), pBitStrm, pErrCode);
	    	break;
	    case 2:
	    	pVal->kind = T_Runtime_Error_decodeerror_PRESENT;
	    	ret = asn1SccT_Int32_Decode((&(pVal->u.decodeerror)), pBitStrm, pErrCode);
	    	break;
	    default:                        /*COVERAGE_IGNORE*/
	        *pErrCode = ERR_UPER_DECODE_T_RUNTIME_ERROR;     /*COVERAGE_IGNORE*/
	        ret = FALSE;                /*COVERAGE_IGNORE*/
	    }
	}  /*COVERAGE_IGNORE*/

	return ret  && asn1SccT_Runtime_Error_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccT_Runtime_Error_ACN_Encode(const asn1SccT_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Runtime_Error_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    switch(pVal->kind)
	    {
	    case T_Runtime_Error_noerror_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 2);
	    	ret = asn1SccT_UInt32_ACN_Encode((&(pVal->u.noerror)), pBitStrm, pErrCode, FALSE);
	    	break;
	    case T_Runtime_Error_encodeerror_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 2);
	    	ret = asn1SccT_Int32_ACN_Encode((&(pVal->u.encodeerror)), pBitStrm, pErrCode, FALSE);
	    	break;
	    case T_Runtime_Error_decodeerror_PRESENT:
	    	BitStream_EncodeConstraintWholeNumber(pBitStrm, 2, 0, 2);
	    	ret = asn1SccT_Int32_ACN_Encode((&(pVal->u.decodeerror)), pBitStrm, pErrCode, FALSE);
	    	break;
	    default: /*COVERAGE_IGNORE*/
	        *pErrCode = ERR_ACN_ENCODE_T_RUNTIME_ERROR;         /*COVERAGE_IGNORE*/
	        ret = FALSE;                    /*COVERAGE_IGNORE*/
	    } /*COVERAGE_IGNORE*/
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_Runtime_Error_ACN_Decode(asn1SccT_Runtime_Error* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	asn1SccSint TASTE_BasicTypes_T_Runtime_Error_index_tmp;

	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &TASTE_BasicTypes_T_Runtime_Error_index_tmp, 0, 2);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_T_RUNTIME_ERROR;
	if (ret) {
	    switch(TASTE_BasicTypes_T_Runtime_Error_index_tmp)
	    {
	    case 0:
	    	pVal->kind = T_Runtime_Error_noerror_PRESENT;
	    	ret = asn1SccT_UInt32_ACN_Decode((&(pVal->u.noerror)), pBitStrm, pErrCode);
	    	break;
	    case 1:
	    	pVal->kind = T_Runtime_Error_encodeerror_PRESENT;
	    	ret = asn1SccT_Int32_ACN_Decode((&(pVal->u.encodeerror)), pBitStrm, pErrCode);
	    	break;
	    case 2:
	    	pVal->kind = T_Runtime_Error_decodeerror_PRESENT;
	    	ret = asn1SccT_Int32_ACN_Decode((&(pVal->u.decodeerror)), pBitStrm, pErrCode);
	    	break;
	    default: /*COVERAGE_IGNORE*/
	        *pErrCode = ERR_ACN_DECODE_T_RUNTIME_ERROR;     /*COVERAGE_IGNORE*/
	        ret = FALSE;                /*COVERAGE_IGNORE*/
	    }
	} /*COVERAGE_IGNORE*/

    return ret && asn1SccT_Runtime_Error_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccT_Int8_Equal(const asn1SccT_Int8* pVal1, const asn1SccT_Int8* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccT_Int8_IsConstraintValid(const asn1SccT_Int8* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((-128LL <= (*(pVal))) && ((*(pVal)) <= 127LL));
    *pErrCode = ret ? 0 :  ERR_T_INT8;

	return ret;
}

#ifdef __cplusplus
const asn1SccT_Int8 asn1SccT_Int8_constant = 0LL;
#endif

void asn1SccT_Int8_Initialize(asn1SccT_Int8* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccT_Int8)asn1SccT_Int8_constant;
}

flag asn1SccT_Int8_Encode(const asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Int8_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, (*(pVal)), -128, 127);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_Int8_Decode(asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, pVal, -128, 127);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_T_INT8;

	return ret  && asn1SccT_Int8_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccT_Int8_ACN_Encode(const asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Int8_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintWholeNumber(pBitStrm, (*(pVal)), -128, 127);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_Int8_ACN_Decode(asn1SccT_Int8* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, pVal, -128, 127);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_T_INT8;

    return ret && asn1SccT_Int8_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccT_UInt8_Equal(const asn1SccT_UInt8* pVal1, const asn1SccT_UInt8* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccT_UInt8_IsConstraintValid(const asn1SccT_UInt8* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 255UL);
    *pErrCode = ret ? 0 :  ERR_T_UINT8;

	return ret;
}

#ifdef __cplusplus
const asn1SccT_UInt8 asn1SccT_UInt8_constant = 0UL;
#endif

void asn1SccT_UInt8_Initialize(asn1SccT_UInt8* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccT_UInt8)asn1SccT_UInt8_constant;
}

flag asn1SccT_UInt8_Encode(const asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_UInt8_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 255);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_UInt8_Decode(asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 255);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_T_UINT8;

	return ret  && asn1SccT_UInt8_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccT_UInt8_ACN_Encode(const asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_UInt8_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 255);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_UInt8_ACN_Decode(asn1SccT_UInt8* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 255);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_T_UINT8;

    return ret && asn1SccT_UInt8_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccT_Boolean_Equal(const asn1SccT_Boolean* pVal1, const asn1SccT_Boolean* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccT_Boolean_IsConstraintValid(const asn1SccT_Boolean* pVal, int* pErrCode)
{
    flag ret = TRUE;
	(void)pVal;
    ret = TRUE;
    *pErrCode = 0;

	return ret;
}

#ifdef __cplusplus
const asn1SccT_Boolean asn1SccT_Boolean_constant = FALSE;
#endif

void asn1SccT_Boolean_Initialize(asn1SccT_Boolean* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccT_Boolean)asn1SccT_Boolean_constant;
}

flag asn1SccT_Boolean_Encode(const asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Boolean_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_AppendBit(pBitStrm,(*(pVal)));
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_Boolean_Decode(asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_ReadBit(pBitStrm, pVal);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_T_BOOLEAN;

	return ret  && asn1SccT_Boolean_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccT_Boolean_ACN_Encode(const asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Boolean_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_AppendBit(pBitStrm,(*(pVal)));
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_Boolean_ACN_Decode(asn1SccT_Boolean* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_ReadBit(pBitStrm, pVal);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_T_BOOLEAN;

    return ret && asn1SccT_Boolean_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccT_Null_Record_Equal(const asn1SccT_Null_Record* pVal1, const asn1SccT_Null_Record* pVal2)
{
	(void)pVal1;
	(void)pVal2;
	return TRUE;

}

flag asn1SccT_Null_Record_IsConstraintValid(const asn1SccT_Null_Record* pVal, int* pErrCode)
{
    flag ret = TRUE;
	(void)pVal;
    ret = TRUE;
    *pErrCode = 0;

	return ret;
}

#ifdef __cplusplus
const asn1SccT_Null_Record asn1SccT_Null_Record_constant = {};
#endif

void asn1SccT_Null_Record_Initialize(asn1SccT_Null_Record* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccT_Null_Record)asn1SccT_Null_Record_constant;
}

flag asn1SccT_Null_Record_Encode(const asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	(void)pBitStrm;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Null_Record_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_Null_Record_Decode(asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;
	(void)pBitStrm;



	return ret  && asn1SccT_Null_Record_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccT_Null_Record_ACN_Encode(const asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;
	(void)pBitStrm;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccT_Null_Record_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccT_Null_Record_ACN_Decode(asn1SccT_Null_Record* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	(void)pBitStrm;
	*pErrCode = 0;



    return ret && asn1SccT_Null_Record_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccPID_Range_Equal(const asn1SccPID_Range* pVal1, const asn1SccPID_Range* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccPID_Range_IsConstraintValid(const asn1SccPID_Range* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 27UL);
    *pErrCode = ret ? 0 :  ERR_PID_RANGE;

	return ret;
}

#ifdef __cplusplus
const asn1SccPID_Range asn1SccPID_Range_constant = 0UL;
#endif

void asn1SccPID_Range_Initialize(asn1SccPID_Range* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccPID_Range)asn1SccPID_Range_constant;
}

flag asn1SccPID_Range_Encode(const asn1SccPID_Range* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccPID_Range_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 27);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccPID_Range_Decode(asn1SccPID_Range* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 27);
	*pErrCode = ret ? 0 : ERR_UPER_DECODE_PID_RANGE;

	return ret  && asn1SccPID_Range_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccPID_Range_ACN_Encode(const asn1SccPID_Range* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccPID_Range_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (*(pVal)), 0, 27);
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccPID_Range_ACN_Decode(asn1SccPID_Range* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, pVal, 0, 27);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_PID_RANGE;

    return ret && asn1SccPID_Range_IsConstraintValid(pVal, pErrCode);
}


flag asn1SccPID_Equal(const asn1SccPID* pVal1, const asn1SccPID* pVal2)
{
	return (*(pVal1)) == (*(pVal2));

}

flag asn1SccPID_IsConstraintValid(const asn1SccPID* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((((((((((((((((((((((((((((((((((((((((((((((((((((((((*(pVal)) == PID_function_1)) || (((*(pVal)) == PID_function_10)))) || (((*(pVal)) == PID_function_11)))) || (((*(pVal)) == PID_function_12)))) || (((*(pVal)) == PID_function_13)))) || (((*(pVal)) == PID_function_14)))) || (((*(pVal)) == PID_function_15)))) || (((*(pVal)) == PID_function_16)))) || (((*(pVal)) == PID_function_17)))) || (((*(pVal)) == PID_function_18)))) || (((*(pVal)) == PID_function_19)))) || (((*(pVal)) == PID_function_2)))) || (((*(pVal)) == PID_function_20)))) || (((*(pVal)) == PID_function_21)))) || (((*(pVal)) == PID_function_22)))) || (((*(pVal)) == PID_function_23)))) || (((*(pVal)) == PID_function_3)))) || (((*(pVal)) == PID_function_4)))) || (((*(pVal)) == PID_function_5)))) || (((*(pVal)) == PID_function_6)))) || (((*(pVal)) == PID_function_7)))) || (((*(pVal)) == PID_function_8)))) || (((*(pVal)) == PID_function_9)))) || (((*(pVal)) == PID_tf_reporter)))) || (((*(pVal)) == PID_testspcc)))) || (((*(pVal)) == PID_teststart00)))) || (((*(pVal)) == PID_uartotherend)))) || (((*(pVal)) == PID_env)));
    *pErrCode = ret ? 0 :  ERR_PID;

	return ret;
}

#ifdef __cplusplus
const asn1SccPID asn1SccPID_constant = PID_function_1;
#endif

void asn1SccPID_Initialize(asn1SccPID* pVal)
{
	(void)pVal;


	(*(pVal)) = (asn1SccPID)asn1SccPID_constant;
}

flag asn1SccPID_Encode(const asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;


	*pErrCode = 0;
	ret = bCheckConstraints ? asn1SccPID_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    switch((*(pVal)))
	    {
	        case PID_function_1:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 0, 0, 27);
	        	break;
	        case PID_function_10:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 1, 0, 27);
	        	break;
	        case PID_function_11:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 2, 0, 27);
	        	break;
	        case PID_function_12:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 3, 0, 27);
	        	break;
	        case PID_function_13:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 4, 0, 27);
	        	break;
	        case PID_function_14:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 5, 0, 27);
	        	break;
	        case PID_function_15:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 6, 0, 27);
	        	break;
	        case PID_function_16:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 7, 0, 27);
	        	break;
	        case PID_function_17:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 8, 0, 27);
	        	break;
	        case PID_function_18:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 9, 0, 27);
	        	break;
	        case PID_function_19:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 10, 0, 27);
	        	break;
	        case PID_function_2:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 11, 0, 27);
	        	break;
	        case PID_function_20:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 12, 0, 27);
	        	break;
	        case PID_function_21:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 13, 0, 27);
	        	break;
	        case PID_function_22:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 14, 0, 27);
	        	break;
	        case PID_function_23:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 15, 0, 27);
	        	break;
	        case PID_function_3:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 16, 0, 27);
	        	break;
	        case PID_function_4:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 17, 0, 27);
	        	break;
	        case PID_function_5:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 18, 0, 27);
	        	break;
	        case PID_function_6:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 19, 0, 27);
	        	break;
	        case PID_function_7:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 20, 0, 27);
	        	break;
	        case PID_function_8:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 21, 0, 27);
	        	break;
	        case PID_function_9:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 22, 0, 27);
	        	break;
	        case PID_tf_reporter:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 23, 0, 27);
	        	break;
	        case PID_testspcc:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 24, 0, 27);
	        	break;
	        case PID_teststart00:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 25, 0, 27);
	        	break;
	        case PID_uartotherend:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 26, 0, 27);
	        	break;
	        case PID_env:
	            BitStream_EncodeConstraintWholeNumber(pBitStrm, 27, 0, 27);
	        	break;
	        default:                    /*COVERAGE_IGNORE*/
	    	    *pErrCode = ERR_UPER_ENCODE_PID; /*COVERAGE_IGNORE*/
	    	    ret = FALSE;            /*COVERAGE_IGNORE*/
	    }
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccPID_Decode(asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;


	{
	    asn1SccSint enumIndex;
	    ret = BitStream_DecodeConstraintWholeNumber(pBitStrm, &enumIndex, 0, 27);
	    *pErrCode = ret ? 0 : ERR_UPER_DECODE_PID;
	    if (ret) {
	        switch(enumIndex)
	        {
	            case 0:
	                (*(pVal)) = PID_function_1;
	                break;
	            case 1:
	                (*(pVal)) = PID_function_10;
	                break;
	            case 2:
	                (*(pVal)) = PID_function_11;
	                break;
	            case 3:
	                (*(pVal)) = PID_function_12;
	                break;
	            case 4:
	                (*(pVal)) = PID_function_13;
	                break;
	            case 5:
	                (*(pVal)) = PID_function_14;
	                break;
	            case 6:
	                (*(pVal)) = PID_function_15;
	                break;
	            case 7:
	                (*(pVal)) = PID_function_16;
	                break;
	            case 8:
	                (*(pVal)) = PID_function_17;
	                break;
	            case 9:
	                (*(pVal)) = PID_function_18;
	                break;
	            case 10:
	                (*(pVal)) = PID_function_19;
	                break;
	            case 11:
	                (*(pVal)) = PID_function_2;
	                break;
	            case 12:
	                (*(pVal)) = PID_function_20;
	                break;
	            case 13:
	                (*(pVal)) = PID_function_21;
	                break;
	            case 14:
	                (*(pVal)) = PID_function_22;
	                break;
	            case 15:
	                (*(pVal)) = PID_function_23;
	                break;
	            case 16:
	                (*(pVal)) = PID_function_3;
	                break;
	            case 17:
	                (*(pVal)) = PID_function_4;
	                break;
	            case 18:
	                (*(pVal)) = PID_function_5;
	                break;
	            case 19:
	                (*(pVal)) = PID_function_6;
	                break;
	            case 20:
	                (*(pVal)) = PID_function_7;
	                break;
	            case 21:
	                (*(pVal)) = PID_function_8;
	                break;
	            case 22:
	                (*(pVal)) = PID_function_9;
	                break;
	            case 23:
	                (*(pVal)) = PID_tf_reporter;
	                break;
	            case 24:
	                (*(pVal)) = PID_testspcc;
	                break;
	            case 25:
	                (*(pVal)) = PID_teststart00;
	                break;
	            case 26:
	                (*(pVal)) = PID_uartotherend;
	                break;
	            case 27:
	                (*(pVal)) = PID_env;
	                break;
	            default:                        /*COVERAGE_IGNORE*/
		            *pErrCode = ERR_UPER_DECODE_PID;     /*COVERAGE_IGNORE*/
		            ret = FALSE;                /*COVERAGE_IGNORE*/
	        }
	    } else {
	        (*(pVal)) = PID_function_1;             /*COVERAGE_IGNORE*/
	    }
	}

	return ret  && asn1SccPID_IsConstraintValid(pVal, pErrCode);
}

flag asn1SccPID_ACN_Encode(const asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints)
{
    flag ret = TRUE;

	asn1SccUint intVal_pVal;
    *pErrCode = 0;
	ret = bCheckConstraints ? asn1SccPID_IsConstraintValid(pVal, pErrCode) : TRUE ;
	if (ret && *pErrCode == 0) {
	    switch((*(pVal))) {
	        case PID_function_1:
	            intVal_pVal = 0UL;
	            break;
	        case PID_function_10:
	            intVal_pVal = 1UL;
	            break;
	        case PID_function_11:
	            intVal_pVal = 2UL;
	            break;
	        case PID_function_12:
	            intVal_pVal = 3UL;
	            break;
	        case PID_function_13:
	            intVal_pVal = 4UL;
	            break;
	        case PID_function_14:
	            intVal_pVal = 5UL;
	            break;
	        case PID_function_15:
	            intVal_pVal = 6UL;
	            break;
	        case PID_function_16:
	            intVal_pVal = 7UL;
	            break;
	        case PID_function_17:
	            intVal_pVal = 8UL;
	            break;
	        case PID_function_18:
	            intVal_pVal = 9UL;
	            break;
	        case PID_function_19:
	            intVal_pVal = 10UL;
	            break;
	        case PID_function_2:
	            intVal_pVal = 11UL;
	            break;
	        case PID_function_20:
	            intVal_pVal = 12UL;
	            break;
	        case PID_function_21:
	            intVal_pVal = 13UL;
	            break;
	        case PID_function_22:
	            intVal_pVal = 14UL;
	            break;
	        case PID_function_23:
	            intVal_pVal = 15UL;
	            break;
	        case PID_function_3:
	            intVal_pVal = 16UL;
	            break;
	        case PID_function_4:
	            intVal_pVal = 17UL;
	            break;
	        case PID_function_5:
	            intVal_pVal = 18UL;
	            break;
	        case PID_function_6:
	            intVal_pVal = 19UL;
	            break;
	        case PID_function_7:
	            intVal_pVal = 20UL;
	            break;
	        case PID_function_8:
	            intVal_pVal = 21UL;
	            break;
	        case PID_function_9:
	            intVal_pVal = 22UL;
	            break;
	        case PID_tf_reporter:
	            intVal_pVal = 23UL;
	            break;
	        case PID_testspcc:
	            intVal_pVal = 24UL;
	            break;
	        case PID_teststart00:
	            intVal_pVal = 25UL;
	            break;
	        case PID_uartotherend:
	            intVal_pVal = 26UL;
	            break;
	        case PID_env:
	            intVal_pVal = 27UL;
	            break;
	        default:                                    /*COVERAGE_IGNORE*/
	            ret = FALSE;                            /*COVERAGE_IGNORE*/
	            *pErrCode = ERR_ACN_ENCODE_PID;                 /*COVERAGE_IGNORE*/
	    }
	    if (ret) {
	    	BitStream_EncodeConstraintPosWholeNumber(pBitStrm, intVal_pVal, 0, 27);
	    }
    } /*COVERAGE_IGNORE*/


    return ret;
}

flag asn1SccPID_ACN_Decode(asn1SccPID* pVal, BitStream* pBitStrm, int* pErrCode)
{
    flag ret = TRUE;
	*pErrCode = 0;

	asn1SccUint intVal_pVal;

	ret = BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (&(intVal_pVal)), 0, 27);
	*pErrCode = ret ? 0 : ERR_ACN_DECODE_PID;
	if (ret) {
	    switch (intVal_pVal) {
	        case 0:
	            (*(pVal)) = PID_function_1;
	            break;
	        case 1:
	            (*(pVal)) = PID_function_10;
	            break;
	        case 2:
	            (*(pVal)) = PID_function_11;
	            break;
	        case 3:
	            (*(pVal)) = PID_function_12;
	            break;
	        case 4:
	            (*(pVal)) = PID_function_13;
	            break;
	        case 5:
	            (*(pVal)) = PID_function_14;
	            break;
	        case 6:
	            (*(pVal)) = PID_function_15;
	            break;
	        case 7:
	            (*(pVal)) = PID_function_16;
	            break;
	        case 8:
	            (*(pVal)) = PID_function_17;
	            break;
	        case 9:
	            (*(pVal)) = PID_function_18;
	            break;
	        case 10:
	            (*(pVal)) = PID_function_19;
	            break;
	        case 11:
	            (*(pVal)) = PID_function_2;
	            break;
	        case 12:
	            (*(pVal)) = PID_function_20;
	            break;
	        case 13:
	            (*(pVal)) = PID_function_21;
	            break;
	        case 14:
	            (*(pVal)) = PID_function_22;
	            break;
	        case 15:
	            (*(pVal)) = PID_function_23;
	            break;
	        case 16:
	            (*(pVal)) = PID_function_3;
	            break;
	        case 17:
	            (*(pVal)) = PID_function_4;
	            break;
	        case 18:
	            (*(pVal)) = PID_function_5;
	            break;
	        case 19:
	            (*(pVal)) = PID_function_6;
	            break;
	        case 20:
	            (*(pVal)) = PID_function_7;
	            break;
	        case 21:
	            (*(pVal)) = PID_function_8;
	            break;
	        case 22:
	            (*(pVal)) = PID_function_9;
	            break;
	        case 23:
	            (*(pVal)) = PID_tf_reporter;
	            break;
	        case 24:
	            (*(pVal)) = PID_testspcc;
	            break;
	        case 25:
	            (*(pVal)) = PID_teststart00;
	            break;
	        case 26:
	            (*(pVal)) = PID_uartotherend;
	            break;
	        case 27:
	            (*(pVal)) = PID_env;
	            break;
	    default:                                    /*COVERAGE_IGNORE*/
	        ret = FALSE;                            /*COVERAGE_IGNORE*/
	        *pErrCode = ERR_ACN_DECODE_PID;                 /*COVERAGE_IGNORE*/
	    }
	} /*COVERAGE_IGNORE*/

    return ret && asn1SccPID_IsConstraintValid(pVal, pErrCode);
}


