/* Body file for function test_cpu_freq
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "test_cpu_freq.h"
#include "../../../../../tf_common/tf_test_results.h"
#include "../../../../../tf_common/tf_cpu.h"
#include <SamRH71Core.h>
#include <stdio.h>


// Access the runtime's processor clock frequency function
extern uint64_t SamRH71Core_GetProcessorClockFrequency(void);


// Constructor
void test_cpu_freq_startup(void)
{
    // Register the test that this TASTE Function will submit a result for
    testresult_register_test(TF_TEST_ID__TestCpuFreqNone);
}


// Handler for cyclic IF: Validates that the application did not get halted on an early gdb breakpoint
void test_cpu_freq_PI_trigger_check(void)
{
    char aMsgBuff[100];
    static asn1SccT_Boolean bResultReported = false;

    // Only do this once
    if (bResultReported) {
        return;
    }

    // If we have 100 MHz then the test has not passed. (we expect 4MHz)
    if (is_processor_clock_100mhz()) {

        // What processor clock speed does TASTE itself think it has?
        uint64_t iProcFreqHertz = SamRH71Core_GetProcessorClockFrequency();
        sprintf(aMsgBuff, "Processor clock frequency is not 100 MHz as expected but rather %llu MHz", iProcFreqHertz / 1000000);
        testresult_report_fail(TF_TEST_ID__TestCpuFreqNone, aMsgBuff);

    } else {
        testresult_report_pass(TF_TEST_ID__TestCpuFreqNone);
    }

    // Report that we already did this
    bResultReported = true;
}


void test_cpu_freq_PI_cyclic2( void ) {
    static int iThing = 0;
    iThing++;
}


