/* Body file for function test_cpu_freq
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "test_cpu_freq.h"
#include "../../../../../tf_common/tf_test_results.h"
#include <SamRH71Core.h>


// Flag to ensure we only report the test result at most once
static asn1SccT_Boolean bResultReported = false;

extern uint64_t SamRH71Core_GetProcessorClockFrequency(void);


// Constructor
void test_cpu_freq_startup(void)
{
    // Register the test that this TASTE Function will submit a result for
    testresult_register_test(TF_TEST_ID__TestCpuFreqNone);

    // What processor clock speed do we think we have?
    uint64_t iProcFreqHertz = SamRH71Core_GetProcessorClockFrequency();
    return;
}


// Handler for cyclic IF: Validates that the application did not get halted on an early gdb breakpoint
void test_cpu_freq_PI_trigger_check(void)
{
    // Only do this once
    if (bResultReported) {
        return;
    }

    // If the test reaches this point then it did not get stopped at a breakpoint, thus its a pass
    testresult_report_pass(TF_TEST_ID__TestCpuFreqNone);

    // Report that we already did this
    bResultReported = true;
}


