/* Body file for function Receiver011
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "receiver011_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void receiver011_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void CInitreceiver011(void);

unsigned receiver011_initialized = 0;
void init_receiver011(void)
{
   if (0 == receiver011_initialized) {
      receiver011_initialized = 1;
      // Call user code startup function
      extern void receiver011_startup(void);
      receiver011_startup();
      receiver011_initialized = 2;
   }
}
void receiver011_PI_1_SR11
      (char *OUT_p1, size_t *OUT_p1_len)

{
   sender_pid = receiver011_pi_1_sr11_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void receiver011_PI_PI_1_SR11
      (asn1SccT_Int32 *);





   // Call user code
   receiver011_PI_PI_1_SR11 ((asn1SccT_Int32 *)OUT_p1);

}

