/* Body file for function Function_23
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "function_23_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void function_23_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void CInitfunction_23(void);

unsigned function_23_initialized = 0;
void init_function_23(void)
{
   if (0 == function_23_initialized) {
      function_23_initialized = 1;
      // Call user code startup function
      extern void function_23_startup(void);
      function_23_startup();
      function_23_initialized = 2;
   }
}
void function_23_PI_2
      (const char *IN_p1, size_t IN_p1_len)

{
   sender_pid = function_23_pi_2_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void function_23_PI_PI_2
      (const asn1SccT_Int32 *);





   // Call user code
   function_23_PI_PI_2 ((asn1SccT_Int32 *)IN_p1);

}




void function_23_PI_CYCLIC(void)
{

   //  Directly call user code, no parameters to pass
   extern void function_23_PI_PI_CYCLIC(void);
   function_23_PI_PI_CYCLIC();
   // puts ("function_23_pi_cyclic called");
}

