/* Header file for function Function_5
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void function_5_startup(void);

/* Provided interfaces */
void function_5_PI_PI_5( const asn1SccT_Int32 * );


void function_5_PI_PI_cyclic_5( void );

/* Required interfaces */
extern void function_5_RI_PI_6( const asn1SccT_Int32 * );


#ifdef __cplusplus
}
#endif
