/* Body file for function TF_Reporter
 * Generated by TASTE (kazoo/model-templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "tf_reporter.h"
#include "../../../../../tf_common/tf_uart_comms.h"
#include "../../../../../tf_common/tf_coverage.h"

/*
 * Constructor
 */
void tf_reporter_startup(void)
{
    // Register the sporadic interface (C function) over which this model can transmit data out from the target hardware
    register_uart_byte_transmitter_function(tf_reporter_RI_samrh71tx);
}

/*
 * Flag to indicate when results have been transmitted. We only want to do that once per run.
 */
static asn1SccT_Boolean iResultsTransmitted = false;

/*
 *
 * Gets called periodically.
 * Checks to see if all registered tests are completed and if so then flushes out the gcov data.
 * Sets a "done" fag so it never does it again
 *
 */
void tf_reporter_PI_PeriodicStarter( void )
{
    // Nothing to do if results already transmitted
    if (iResultsTransmitted) {
        return;
    }

    // TODO: Add polling of the test_results objec to see whether all registered tests are now complete.
    // If not complete, return here

    // Send a sample message
    transmit_log_info("Hello New York!!!");

    // Transmit all gcov data over UARTS
    coverage_transmit_all();

    // Set the flag so we don't do this again
    iResultsTransmitted = true;
}

