/* Body file for function Sender009
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "sender009.h"
//#include <stdio.h>


void sender009_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[Sender009] Startup");
}

void sender009_PI_PI_1(void)
{
    asn1SccT_Int32 Parameter_N = 0;


    // TestStart000 shall invoke this function, which shall send
    // a message to Receiver001 as part of requirement MBEP-RT-FUN-220
    // and MBEP-RT-FUN-220, where 1:10 sender functions send to one
    // receiver function.

    Parameter_N = 900;
    sender009_RI_PI_9( &Parameter_N );
}


