/* Header file for function BootHelper00F
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void boothelper00f_startup(void);

/* Provided interfaces */
void boothelper00f_PI_PI_1_Boot_Helper( asn1SccT_Int32 *, asn1SccT_Boolean * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
