/* Body file for function RcvACN03
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "rcvacn03_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void rcvacn03_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void CInitrcvacn03(void);

unsigned rcvacn03_initialized = 0;
void init_rcvacn03(void)
{
   if (0 == rcvacn03_initialized) {
      rcvacn03_initialized = 1;
      // Call user code startup function
      extern void rcvacn03_startup(void);
      rcvacn03_startup();
      rcvacn03_initialized = 2;
   }
}
void rcvacn03_PI_1_ACN03
      (const char *IN_p1, size_t IN_p1_len,
       char *OUT_p2, size_t *OUT_p2_len)

{
   sender_pid = rcvacn03_pi_1_acn03_get_sender();
   
   asn1SccT_Boolean IN_P1;
   int p1_error_code = 0;

   if (0 != Decode_ACN_T_Boolean (&IN_P1, (void *)IN_p1, IN_p1_len, &p1_error_code)) {
      return;
   }
   
   asn1SccT_Boolean OUT_P2;

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void rcvacn03_PI_PI_1_ACN03
      (const asn1SccT_Boolean *,
       asn1SccT_Boolean *);





   // Call user code
   rcvacn03_PI_PI_1_ACN03 (&IN_P1, &OUT_P2);

   int p2_error_code = 0;
   *OUT_p2_len = Encode_ACN_T_Boolean
      ((void *)OUT_p2,
       asn1SccT_Boolean_REQUIRED_BYTES_FOR_ACN_ENCODING,
       &OUT_P2,
       &p2_error_code);
}

