/* Body file for function BootHelper00F
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "boothelper00f_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void boothelper00f_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void CInitboothelper00f(void);

unsigned boothelper00f_initialized = 0;
void init_boothelper00f(void)
{
   if (0 == boothelper00f_initialized) {
      boothelper00f_initialized = 1;
      // Call user code startup function
      extern void boothelper00f_startup(void);
      boothelper00f_startup();
      boothelper00f_initialized = 2;
   }
}
void boothelper00f_PI_1
      (char *OUT_p1, size_t *OUT_p1_len,
       char *OUT_p2, size_t *OUT_p2_len)

{
   sender_pid = boothelper00f_pi_1_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void boothelper00f_PI_PI_1
      (asn1SccT_Int32 *,
       asn1SccT_Boolean *);





   // Call user code
   boothelper00f_PI_PI_1 ((asn1SccT_Int32 *)OUT_p1, (asn1SccT_Boolean *)OUT_p2);

}

