/* Body file for function layer_4_f5
 * Generated by KISPE's test model C code scaffolder
 */

#include "layer_4_f5.h"
#include <stdio.h>


// Use the layer number to determine the next function to call in the chain
static const asn1SccT_UInt32 iMyLayerNumber = 4; 
static const asn1SccT_UInt32 iMyFunctionNumber = 5; 


// Constructor (unused)
void layer_4_f5_startup(void)
{
}


// Protected interface implementation. No parameters.
// Simply calls the next layer
void layer_4_f5_PI_prot(void)
{
    // Call the next layer in the chain
    layer_4_f5_RI_prot();
}


