/* Body file for function Function_5
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "function_5_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void function_5_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void CInitfunction_5(void);

unsigned function_5_initialized = 0;
void init_function_5(void)
{
   if (0 == function_5_initialized) {
      function_5_initialized = 1;
      // Call user code startup function
      extern void function_5_startup(void);
      function_5_startup();
      function_5_initialized = 2;
   }
}
void function_5_PI_5
      (const char *IN_p1, size_t IN_p1_len)

{
   sender_pid = function_5_pi_5_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void function_5_PI_PI_5
      (const asn1SccT_Int32 *);





   // Call user code
   function_5_PI_PI_5 ((asn1SccT_Int32 *)IN_p1);

}




void function_5_PI_cyclic_5(void)
{

   //  Directly call user code, no parameters to pass
   extern void function_5_PI_PI_cyclic_5(void);
   function_5_PI_PI_cyclic_5();
   // puts ("function_5_pi_cyclic_5 called");
}

