/* Header file for function RcvACN01
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void rcvacn01_startup(void);

/* Provided interfaces */
void rcvacn01_PI_PI_1_ACN_01( const asn1SccT_Int32 *, asn1SccT_Int32 * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
