/* Body file for function layer_6_f4
 * Generated by KISPE's test model C code scaffolder
 */

#include "layer_6_f4.h"
#include <stdio.h>


// Use the layer number to determine the next function to call in the chain
static const asn1SccT_UInt32 iMyLayerNumber = 6; 
static const asn1SccT_UInt32 iMyFunctionNumber = 4; 


// Constructor (unused)
void layer_6_f4_startup(void)
{
}


// Protected interface implementation. No parameters.
// Simply calls the next layer
void layer_6_f4_PI_prot(void)
{
    // Call the next layer in the chain
    layer_6_f4_RI_prot();
}


