/* Body file for function Prot05IFOUT
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "prot05ifout.h"
#include <limits.h>
//#include <stdio.h>


void prot05ifout_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[Prot05IFOUT] Startup");
}

void prot05ifout_PI_PI_1_5OUT
      (asn1SccT_Int32 *OUT_p1,
       asn1SccT_UInt32 *OUT_p2,
       asn1SccT_UInt8 *OUT_p3,
       asn1SccT_Int8 *OUT_p4,
       asn1SccT_Boolean *OUT_p5)

{
    // --
    // -- MBEP-RT-FUN-160
    // -- Two Test Functions, five out parameters from the
    // -- protected interface under test.


    *OUT_p1 = INT_MIN;

    *OUT_p2 = 0;

    *OUT_p3 = 0;

    *OUT_p4 = SCHAR_MIN;

    *OUT_p5 = false;


}


