/* Body file for function layer_8_f4
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "layer_8_f4.h"
//#include <stdio.h>


void layer_8_f4_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[layer_8_f4] Startup");
}

void layer_8_f4_PI_prot(void)
{
   // Write your code here
}


