/* Header file for function partition_1_Timer_Manager
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm_if-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

/* The purpose of this file is to provide a wrapper around the user code,
 * with a single interface that is independent of the implementation language
 * of the function. The parameters of each PI are blackboxes encoded
 * in the form specified in the interface view (Native, uPER, or ACN)
*/

#pragma once
#if defined(__unix__) || defined (__MSP430__)
   #include <stdlib.h>
   #include <stdio.h>
#else
   typedef unsigned size_t;
#endif

#include "C_ASN1_Types.h"
#ifdef __cplusplus
extern "C" {
#endif


// Function initialization - calls user startup code of all dependent functions
void init_partition_1_timer_manager(void);


/* Provided interfaces */
void partition_1_timer_manager_RESET_testsdl08_mytime(void);


void partition_1_timer_manager_RESET_testsdl14_mytime(void);


void partition_1_timer_manager_SET_testsdl08_mytime
      (const char *IN_val, size_t IN_val_len);



void partition_1_timer_manager_SET_testsdl14_mytime
      (const char *IN_val, size_t IN_val_len);



void partition_1_timer_manager_Tick(void);


#ifdef __cplusplus
}
#endif

