/* Body file for function layer_9_f5
 * Generated by KISPE's test model C code scaffolder
 */

#include "layer_9_f5.h"
#include "../../../../../tf_common/tf_uart_comms.h"
#include <stdio.h>


// Use the layer number to determine the next function to call in the chain
static const asn1SccT_UInt32 iMyLayerNumber = 9; 
static const asn1SccT_UInt32 iMyFunctionNumber = 5; 


// Constructor (unused)
void layer_9_f5_startup(void)
{
}


// Protected interface implementation. No parameters.
// Simply calls the next layer
void layer_9_f5_PI_prot(void)
{
    // Call the next layer in the chain
    layer_9_f5_RI_prot();

    // Send a hello message over the UART channel, but only for one function per layer to avoid cluttering the output
    if (iMyFunctionNumber == 10) {
        char aMsgBuff[100];
        sprintf(aMsgBuff, "Layer %u >> Function %u", iMyLayerNumber, iMyFunctionNumber);
        transmit_log_info(aMsgBuff);
    }
}


