INCLUDEPATH += work/dataview/C
HEADERS += work/dataview/C/dataview-uniq.h
HEADERS += work/dataview/Ada/src/*.ads
include(function_1/function_1.pro)
include(function_10/function_10.pro)
include(function_11/function_11.pro)
include(function_12/function_12.pro)
include(function_13/function_13.pro)
include(function_14/function_14.pro)
include(function_15/function_15.pro)
include(function_16/function_16.pro)
include(function_17/function_17.pro)
include(function_18/function_18.pro)
include(function_19/function_19.pro)
include(function_2/function_2.pro)
include(function_20/function_20.pro)
include(function_21/function_21.pro)
include(function_22/function_22.pro)
include(function_23/function_23.pro)
include(function_3/function_3.pro)
include(function_4/function_4.pro)
include(function_5/function_5.pro)
include(function_6/function_6.pro)
include(function_7/function_7.pro)
include(function_8/function_8.pro)
include(function_9/function_9.pro)
include(testspcc/testspcc.pro)
include(teststart00/teststart00.pro)
include(tf_reporter/tf_reporter.pro)
include(uartotherend/uartotherend.pro)

