/* Body file for function Function_34
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "function_34_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void function_34_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void adainit(void);

extern void init_function_42(void);
extern unsigned function_42_initialized;
unsigned function_34_initialized = 0;
void init_function_34(void)
{
   if (0 == function_34_initialized) {
      function_34_initialized = 1;
      // Call user code startup function
      extern void function_34_startup(void);
      function_34_startup();
      // Iterate over all synchronous RIs, and call their parent's
      // init function. Multiple calls are prevented by the "init" guard.
      if (0 == function_42_initialized) {
          init_function_42();
      }
      function_34_initialized = 2;
   }
}
void function_34_PI_1
      (const char *IN_p1, size_t IN_p1_len)

{
   sender_pid = function_34_pi_1_get_sender();

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void function_34_PI_PI_1
      (const asn1SccMyInteger *);





   // Call user code
   function_34_PI_PI_1 ((asn1SccMyInteger *)IN_p1);

}

