/* Header file for function Function_29
 * Generated by TASTE (kazoo/templates/skeletons/c-header/function.tmplt)
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif


void function_29_startup(void);

/* Provided interfaces */
void function_29_PI_PI_1_CYCLIC( void );


void function_29_PI_PI_2( const asn1SccT_Int32 * );

/* Required interfaces */
extern void function_29_RI_PI_2( const asn1SccT_Int32 * );


#ifdef __cplusplus
}
#endif
