/* Body file for function Receiver015
 * Generated by TASTE (kazoo/templates/skeletons/c-body/function.tmplt)
 * You can edit this file, it will not be overwritten

    !! IMPORTANT                                                        !!
    !! When you modify your design (interface view), you must update    !!
    !! the procedures corresponding to the provided interfaces in this  !!
    !! file. The up-to-date signatures can be found in the header file. !!
*/
#include "receiver015.h"
//#include <stdio.h>


void receiver015_startup(void)
{
   // Write your initialisation code
   // You may call sporadic required interfaces and start timers
   // puts ("[Receiver015] Startup");
}

void receiver015_PI_PI_1_SR15 ( const asn1SccT_Int32 *Parameter, asn1SccT_Boolean *test_check )

{

    if ( *Parameter == 600 )
    {
        *test_check = true;
    }
    else
    {
        *test_check = false;
    }
}


