/* Body file for function Example_Test_Function
 * Generated by TASTE (kazoo/templates/glue/language_wrappers/vm-if-body/function.tmplt)
 */
#include "example_test_function_vm_if.h"
#include "routing.h"

// Define a global PID variable used to keep track of the sender of the last message
static asn1SccPID sender_pid = PID_env;

// API to provide to the user code the PID of the last PI caller
void example_test_function_get_sender(asn1SccPID *OUT_sender_pid, asn1SccPID unused)
{
  *OUT_sender_pid = sender_pid;
}



extern void adainit(void);

unsigned example_test_function_initialized = 0;
void init_example_test_function(void)
{
   if (0 == example_test_function_initialized) {
      example_test_function_initialized = 1;
      // Call user code startup function
      extern void example_test_function_startup(void);
      example_test_function_startup();
      example_test_function_initialized = 2;
   }
}
void example_test_function_trigger(void)
{

   //  Directly call user code, no parameters to pass
   extern void example_test_function_PI_trigger(void);
   example_test_function_PI_trigger();
   // puts ("example_test_function_trigger called");
}

